### ISSUE TITLE
Distilled SDXL from segmind doesn't work

### ISSUE THREAD

**Issue by CyberTimon** [comfyanonymous/ComfyUI#1827]
Hello!

When trying to load segmind/SSD-1B safetensors it throws this error: 

```
ERROR: Could not detect model type of: /home/cybertimon/Repositories/AiModels/DiffusionModels/XL_SSD-1B.safetensors

File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/cybertimon/Repositories/ComfyUI/nodes.py", line 476, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "/home/cybertimon/Repositories/ComfyUI/comfy/sd.py", line 415, in load_checkpoint_guess_config
raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
```

I think it's because SSD-1B isn't directly SDXL but is the same architecture. 
Please add support for SSD-1B or tell me how to fix it, as it looks like an amazing model.

Thanks!

**Comment by Piezoid** [comment]
Surprisingly, this is enough for ComfyUI to accept their .safetensor. More work likely required,  I haven't delved into the model specifics yet.

```patch
diff --git a/comfy/supported_models.py b/comfy/supported_models.py
index bb8ae21..1f65ee9 100644
--- a/comfy/supported_models.py
+++ b/comfy/supported_models.py
@@ -189,5 +189,13 @@ class SDXL(supported_models_base.BASE):
     def clip_target(self):
         return supported_models_base.ClipTarget(sdxl_clip.SDXLTokenizer, sdxl_clip.SDXLClipModel)
 
+class SSD1B(SDXL):
+    unet_config = {
+        "model_channels": 320,
+        "use_linear_in_transformer": True,
+        "transformer_depth": [0, 2, 4], # SDXL is [0, 2, 10] here
+        "context_dim": 2048,
+        "adm_in_channels": 2816
+    }
 
-models = [SD15, SD20, SD21UnclipL, SD21UnclipH, SDXLRefiner, SDXL]
+models = [SD15, SD20, SD21UnclipL, SD21UnclipH, SDXLRefiner, SDXL, SSD1B]
```

**Comment by CyberTimon** [comment]
Thank you very much! Will test this out tomorrow 👍

**Comment by jav12z** [comment]
> Surprisingly, this is enough for ComfyUI to accept their .safetensor. More work likely required, I haven't delved into the model specifics yet.
> 
> ```diff
> diff --git a/comfy/supported_models.py b/comfy/supported_models.py
> index bb8ae21..1f65ee9 100644
> --- a/comfy/supported_models.py
> +++ b/comfy/supported_models.py
> @@ -189,5 +189,13 @@ class SDXL(supported_models_base.BASE):
>      def clip_target(self):
>          return supported_models_base.ClipTarget(sdxl_clip.SDXLTokenizer, sdxl_clip.SDXLClipModel)
>  
> +class SSD1B(SDXL):
> +    unet_config = {
> +        "model_channels": 320,
> +        "use_linear_in_transformer": True,
> +        "transformer_depth": [0, 2, 4], # SDXL is [0, 2, 10] here
> +        "context_dim": 2048,
> +        "adm_in_channels": 2816
> +    }
>  
> -models = [SD15, SD20, SD21UnclipL, SD21UnclipH, SDXLRefiner, SDXL]
> +models = [SD15, SD20, SD21UnclipL, SD21UnclipH, SDXLRefiner, SDXL, SSD1B]
> ```

I obtain pitch black pictures using this. At least it doesn't give an error.

**Comment by Gothos** [comment]
Hi! One of the creators of SSD here! Unfortunately the above approach won't fully work, some layers will not load in. The U-Net is somewhat different from SDXL, though it's based off of it. A few changes might be required to load it in. I'll link the diffusers PR that was required to load it in, perhaps that will help anyone trying to load it in:
https://github.com/huggingface/diffusers/pull/5400

**Comment by Piezoid** [comment]
> Hi! One of the creators of SSD here! Unfortunately the above approach won't fully work, some layers will not load in. The U-Net is somewhat different from SDXL, though it's based off of it. A few changes might be required to load it in. I'll link the diffusers PR that was required to load it in, perhaps that will help anyone trying to load it in: [huggingface/diffusers#5400](https://github.com/huggingface/diffusers/pull/5400) Essentially our U-Net isn't fully symmetrical, and some weights get left out trying to load in the weights with the above manner

Thanks for passing by!

I think I managed to correctly load the transformers on the [up-sample side](https://github.com/comfyanonymous/ComfyUI/blob/434ce25e/comfy/ldm/modules/diffusionmodules/openaimodel.py#L522-L596) by hard-coding the depth as a PoC:
<details>

```diff
diff --git a/comfy/ldm/modules/diffusionmodules/openaimodel.py b/comfy/ldm/modules/diffusionmodules/openaimodel.py
index bf58a40..b212d2a 100644
--- a/comfy/ldm/modules/diffusionmodules/openaimodel.py
+++ b/comfy/ldm/modules/diffusionmodules/openaimodel.py
@@ -500,23 +500,27 @@ class UNetModel(nn.Module):
                 device=device,
                 operations=operations
             ),
-            SpatialTransformer(  # always uses a self-attn
-                            ch, num_heads, dim_head, depth=transformer_depth_middle, context_dim=context_dim,
-                            disable_self_attn=disable_middle_self_attn, use_linear=use_linear_in_transformer,
-                            use_checkpoint=use_checkpoint, dtype=self.dtype, device=device, operations=operations
-                        ),
-            ResBlock(
-                ch,
-                time_embed_dim,
-                dropout,
-                dims=dims,
-                use_checkpoint=use_checkpoint,
-                use_scale_shift_norm=use_scale_shift_norm,
-                dtype=self.dtype,
-                device=device,
-                operations=operations
-            ),
-        )
+        ]
+        if transformer_depth_middle > 0: # This likely breaks SDXL_small_cnet, this might require a new flag
+            layers.extend([
+                SpatialTransformer(  # always uses a self-attn
+                                ch, num_heads, dim_head, depth=transformer_depth_middle, context_dim=context_dim,
+                                disable_self_attn=disable_middle_self_attn, use_linear=use_linear_in_transformer,
+                                use_checkpoint=use_checkpoint, dtype=self.dtype, device=device, operations=operations
+                            ),
+                ResBlock(
+                    ch,
+                    time_embed_dim,
+                    dropout,
+                    dims=dims,
+                    use_checkpoint=use_checkpoint,
+                    use_scale_shift_norm=use_scale_shift_norm,
+                    dtype=self.dtype,
+                    device=device,
+                    operations=operations
+                ),
+            ])
+        self.middle_block = TimestepEmbedSequential(*layers)
         self._feature_size += ch
 
         self.output_blocks = nn.ModuleList([])
@@ -551,11 +555,17 @@ class UNetModel(nn.Module):
                         disabled_sa = disable_self_attentions[level]
                     else:
                         disabled_sa = False
 
+                    td = transformer_depth[level]
+                    if level==2 and i == 2: #XXX: hardcoded PoC
+                        td = 10
+                    if level == 1:
+                        td = 1
+                        if i == 0:
+                            td = 2
                     if not exists(num_attention_blocks) or i < num_attention_blocks[level]:
                         layers.append(
                             SpatialTransformer(
-                                ch, num_heads, dim_head, depth=transformer_depth[level], context_dim=context_dim,
+                                ch, num_heads, dim_head, depth=td, context_dim=context_dim,
                                 disable_self_attn=disabled_sa, use_linear=use_linear_in_transformer,
                                 use_checkpoint=use_checkpoint, dtype=self.dtype, device=device, operations=operations
                             )

```

(Of course, this needs to be properly done by extending the UNet config)
</details>

The second `ResBlock` in `middle_block` is also skipped. 
Someone could use this as a starting point for adding new UNet configuration fields.

The results do look a lot better, yet I find interesting how resnets are resilient to misconfiguration.

The text conditioner network is also not loading correctly:
```
missing {'cond_stage_model.clip_g.logit_scale', 'cond_stage_model.clip_g.text_projection', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['conditioner.embedders.1.model.text_model.embeddings.position_ids', 'conditioner.embedders.1.model.text_projection.weight', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
```

> I obtain pitch black pictures using this. At least it doesn't give an error.

@jav12z Yes, I've been getting these. I failed pinpoint when this happens, while copying a working workflow to another outputting black image. Once it happens, it poison the instance, causing all workflow to produce black images.
As the model loading is very incomplete with my naive patch, anything can happens.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/6ec3f12c6e2e1d214c41f5713308818541da52a4

It should work now.

**Comment by ameen-roayan** [comment]
Hi still getting this error 

r occurred when executing CheckpointLoaderSimple:

ERROR: Could not detect model type of: F:\AI\Automatic1111\stable-diffusion-webui\models/Stable-diffusion\segmindSSD1B_v10.safetensors

File "F:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI\ComfyUI\nodes.py", line 476, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 415, in load_checkpoint_guess_config
raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))

**Comment by CyberTimon** [comment]
> Hi still getting this error
> 
> r occurred when executing CheckpointLoaderSimple:
> 
> ERROR: Could not detect model type of: F:\AI\Automatic1111\stable-diffusion-webui\models/Stable-diffusion\segmindSSD1B_v10.safetensors
> 
> File "F:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI\ComfyUI\nodes.py", line 476, in load_checkpoint out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings")) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 415, in load_checkpoint_guess_config raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))

Are you on the latest commit? Otherwise update it or execute `git pull` in the comfyui directory.
