### ISSUE TITLE
Some recent changes have caused my workflow to generate images very poorly

### ISSUE THREAD

**Issue by mijuku233** [comfyanonymous/ComfyUI#1881]
My workflow contains a custom node: [ComfyUI-Latent-Modifiers](https://github.com/Clybius/ComfyUI-Latent-Modifiers)，
and some recent updates have resulted in very bad images being generated when using it.

Although I have already submitted an issue to that custom node project, the issue may not be resolved, so I'm submitting the issue here as well.
Some recent updates have made the KSampler generate different images than before, and I'd love to see comfyui get better by making major changes, but I think some of the old stuff should be kept, like an `old KSampler` that generates the same images as before.

**Comment by comfyanonymous** [comment]
Should be fixed with: https://github.com/comfyanonymous/ComfyUI/commit/d2e27b48f169b0e5def6b9b2c7874e4010282921

**Comment by mijuku233** [comment]
> Should be fixed with: [d2e27b4](https://github.com/comfyanonymous/ComfyUI/commit/d2e27b48f169b0e5def6b9b2c7874e4010282921)

This update fixes `sharpness` in Latent-Modifiers, but still doesn't fix `contrast`.

**Comment by Clybius** [comment]
Many thanks for working on this, Comfy! 

I can confirm that there are still some (albeit much lesser) issues relating to functionality.

Some pretext/TL;DR of the current situation: After doing some fixing from the timestep arg change, previous functionality seems to *mostly* work with the exception of a few important features: `contrast`, `sharpness`, and `divisive normalization`. These functions now seem to introduce noisy artifacts in the image at moderate values where they wouldn't previously, interestingly enough.


I was able to somewhat work around this issue with `contrast` by adding the input arg to its function, and later subtracting the input arg, as so: `contrast_func(noise_pred_degraded + args["input"]) - args["input"]`. 

Though this seems to make it function somewhat as previous, there appears to be extra noise left-over, with incrementing amounts as you increase the multiplier value for `contrast`. This issue appears to happen with `sharpness` (operates on `cond`, and `uncond` if the user chooses), `contrast` (operates on `cond - uncond`) at any value when unchanged, and `divisive normalization` (operates on the final equation of `uncond + noise_pred * cond_scale`).

Further testing with `input - cond` and `input - uncond` (idea from this commit in [sd-dynamic-thresholding](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/2998d4c074ede2bf59cb8c7c207c418687f165e7)) when the variables are introduced seems to yield some "here be dragons"-esque changes, such as darkening the image with `sharpness` which wouldn't happen previously.

For now, I can push a change somewhat working around the noise issue, though input on any possible solutions would be much appreciated.
