### ISSUE TITLE
'ModelSamplingConfig' object has no attribute 'sampling_settings'

### ISSUE THREAD

**Issue by MartinBTM** [comfyanonymous/ComfyUI#2038]
Error occurred when executing KSampler:

'ModelSamplingConfig' object has no attribute 'sampling_settings'

File "/mnt/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/ComfyUI/nodes.py", line 1286, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
File "/mnt/ComfyUI/nodes.py", line 1256, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "/mnt/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 195, in animatediff_sample
model.model.model_sampling = BetaSchedules.to_model_sampling(params.beta_schedule, model)
File "/mnt/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_utils.py", line 59, in to_model_sampling
ms_obj = model_sampling(cls.to_config(alias), model_type=model.model.model_type)
File "/mnt/ComfyUI/comfy/model_base.py", line 33, in model_sampling
return ModelSampling(model_config)
File "/mnt/ComfyUI/comfy/model_sampling.py", line 27, in __init__
beta_schedule = model_config.sampling_settings.get("beta_schedule", beta_schedule)

How can I fix the problem?

**Comment by comfyanonymous** [comment]
Update both ComfyUI and ComfyUI-AnimateDiff-Evolved.

**Comment by MartinBTM** [comment]
> Update both ComfyUI and ComfyUI-AnimateDiff-Evolved.
I have updated all , but also the same error

**Comment by kichinto** [comment]
yes ,many hours ago there are still have problems. but now it's solved. It work.

**Comment by makeratl** [comment]
I'm getting this same error today - I thought it was a fresh rebuild I did of ComfyUI, but it persist even on a version that was previously working.

**Comment by jamesmgg** [comment]
getting the same error too

**Comment by jamesmgg** [comment]
btw, I was getting this error and doing a git pull on comfy UI's master branch solved it for me

**Comment by LankyPoet** [comment]
Confirming that I just updated all tonight (just 10 minutes prior to this post) and I am still receiving this error.

**Comment by MartinBTM** [comment]
I setup a new Comfyui and download again, and it works

**Comment by 4lt3r3go** [comment]
same error here. i removed animatediff, reinstalled, removed animatediff evovledm reinstalled, tryed everything. still errors

**Comment by vrgz2022** [comment]
me too

**Comment by KeithHanson** [comment]
Happening to me too, latest commit hash on both ComfyUI and Evolved

**Comment by gaodianzhuo** [comment]
me too

**Comment by AInseven** [comment]
I fixed this by: Manager -> Update All

**Comment by Kosinkadink** [comment]
Hey, I'll chime in here since this is still getting mentioned here. For ComfyUI-AnimateDiff-Evolved, I implemented the update to fix this within hours of the ComfyUI update. If you get this error while using AnimateDiff-Evolved, you just needed to update AnimateDiff-Evolved and ComfyUI, and you're good to go. Whenever there is a new ComfyUI update that makes non-backwards compatible changes, I try to push a new version of AnimateDiff-Evolved out a few hours later.

Some peeps here are using the other custom nodes that I'm not managing, comfyui-animatediff. All I can recommend is switching over to [ComfyUI-AnimateDiff-Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved ). In addition to working the same (my code is used in the comfyui-animatediff repo, too), AnimateDiff-Evolved supports HotshotXL and AnimateDiff-SDXL, as well as some additional motion controls like motion_scale. It also is usable with most KSamplers, just need to use the AnimateDiff Loader node on the model. Soon it will also support Custom KSampler nodes as well. And I actively maintain it, which means the latest version of AnimateDiff-Evolved is never but a few hours incompatible with the latest ComfyUI version.

**Comment by TanvirHafiz** [comment]
> Hey, I'll chime in here since this is still getting mentioned. For ComfyUI-AnimateDiff-Evolved, I implemented the update to fix this within hours of the ComfyUI update. If you get this error while using AnimateDiff-Evolved, you just needed to update AnimateDiff-Evolved and ComfyUI, and you're good to go. Whenever there is a new ComfyUI update that makes non-backwards compatible changes, I try to push a new version of AnimateDiff-Evolved out a few hours later.
> 
> Some peeps here are using the other custom nodes that I'm not managing, comfyui-animatediff. All I can recommend is switching over to [ComfyUI-AnimateDiff-Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved). In addition to working the same (my code is used in the comfyui-animatediff repo, too), AnimateDiff-Evolved supports HotshotXL and AnimateDiff-SDXL motion modules, as well as some additional motion controls like motion_scale. It also is usable with most KSamplers, just need to use the AnimateDiff Loader node on the model. Soon it will also support Custom KSampler nodes as well. And I actively maintain it, which means the latest version of AnimateDiff-Evolved is never but a few hours incompatible with the latest ComfyUI version.

hi, can you tell me how to update the animatediff evolved separetly? I have just updated comfy, i am pretty sure that didnt update the extensions
