### ISSUE TITLE
Has anyone encountered the issue of generating blank images with ComfyUI on Mac M2?

### ISSUE THREAD

**Issue by laochake** [comfyanonymous/ComfyUI#2273]
Has anyone encountered the issue of generating blank images with ComfyUI? Mac M2, when loading the default workflow.
The startup command is not using "python [main.py](https://main.py/) --force-fp16" because it crashes when generating images. Instead, we are using "python [main.py](https://main.py/)".

![image](https://github.com/comfyanonymous/ComfyUI/assets/22712340/0c406e14-8483-48f8-a57c-4ac79d14bd83)

**Comment by cyLi-Tiger** [comment]
Mac M1 Pro, same problem, any clues?

**Comment by cyLi-Tiger** [comment]
> Mac M1 Pro, same problem, any clues?"

--cpu can work but super slow.

**Comment by cyLi-Tiger** [comment]
> > Mac M1 Pro, same problem, any clues?"
> 
> --cpu can work but super slow.

Fixed after update to macOS Sonoma

**Comment by kaiGit** [comment]
The issue regressed on macOS Sonoma 14.4. --cpu is still a viable workaround.

**Comment by coletree** [comment]
> The issue regressed on macOS Sonoma 14.4. --cpu is still a viable workaround.该问题在 macOS Sonoma 14.4 上回归。 --cpu 仍然是一个可行的解决方法。

the same problem ... but it still doesn't work on my macOS Sonoma 14.4 ? what can i do ?

**Comment by vennetong** [comment]
I found dpmpp-sde can generate image with sdxl models, but this sampling method cannot work with sd15 models very well.

**Comment by francisjervis** [comment]
See https://github.com/comfyanonymous/ComfyUI/issues/2992

**Comment by kekekekekeshi** [comment]
同样的
