### ISSUE TITLE
Running workflows broken after the Execution Model Inversion merge

### ISSUE THREAD

**Issue by sanguivore-easyco** [comfyanonymous/ComfyUI#4378]
### Expected Behavior

The default workflow works

### Actual Behavior

The default workflow fails with
```
Error occurred when executing CheckpointLoaderSimple:

map_node_over_list() got an unexpected keyword argument 'execution_block_cb'

File "/home/ubuntu/ComfyUI/execution.py", line 313, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/home/ubuntu/ComfyUI/execution.py", line 188, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
```

### Steps to Reproduce

- pull main and run/restart ComfyUI (on the latest commit, currently `5960f946a9353f4a8ff97e92f82e0541caa32bf7`)
- Load the Default Workflow
- Trigger the Workflow

I do have a lot of custom nodes, but I the error message seems unrelated to them, nonetheless, you can see which ones I have in the debug logs

### Debug Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2024-08-15 16:06] ** ComfyUI startup time: 2024-08-15 16:06:16.947560
[2024-08-15 16:06] ** Platform: Linux
[2024-08-15 16:06] ** Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
[2024-08-15 16:06] ** Python executable: /usr/bin/python3
[2024-08-15 16:06] ** ComfyUI Path: /home/ubuntu/ComfyUI
[2024-08-15 16:06] ** Log path: /home/ubuntu/ComfyUI/comfyui.log
[2024-08-15 16:06] 
Prestartup times for custom nodes:
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/rgthree-comfy
[2024-08-15 16:06]    2.7 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-08-15 16:06] 
Total VRAM 22503 MB, total RAM 31734 MB
[2024-08-15 16:06] pytorch version: 2.3.0+cu121
[2024-08-15 16:06] xformers version: 0.0.26.post1
[2024-08-15 16:06] Set vram state to: HIGH_VRAM
[2024-08-15 16:06] Device: cuda:0 NVIDIA A10G : cudaMallocAsync
[2024-08-15 16:06] Using xformers cross attention
[2024-08-15 16:06] [Prompt Server] web root: /home/ubuntu/ComfyUI/web
[2024-08-15 16:06] NumExpr defaulting to 8 threads.
[2024-08-15 16:06] EXTENDING PATH WITH /home/ubuntu/.local/lib/python3.10/site-packages/deforum/models/depth_models
[2024-08-15 16:06] Endpoint /tmp/29a445e0093392075de84d6c51a49a49/{filename} registered for serving files from /tmp/tmpxtpehfu7
[2024-08-15 16:06] [deforum] Execution HiJack Active
[2024-08-15 16:06] [Allor]: 0 standard nodes was overridden.
[2024-08-15 16:06] /home/ubuntu/.local/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)

[2024-08-15 16:06] [Allor]: 12 modules enabled.
[2024-08-15 16:06] [Allor]: 98 nodes was loaded.
[2024-08-15 16:06] !! Trying to start the node
[2024-08-15 16:06] /home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
[2024-08-15 16:06] # 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
[2024-08-15 16:06] # 😺dzNodes: LayerStyle -> Warning: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/resource_dir.ini not found, default directory to be used. 
[2024-08-15 16:06] # 😺dzNodes: LayerStyle -> Find 1 LUTs in /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/lut
[2024-08-15 16:06] # 😺dzNodes: LayerStyle -> Find 1 Fonts in /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/font
[2024-08-15 16:06] Total VRAM 22503 MB, total RAM 31734 MB
[2024-08-15 16:06] pytorch version: 2.3.0+cu121
[2024-08-15 16:06] xformers version: 0.0.26.post1
[2024-08-15 16:06] Set vram state to: HIGH_VRAM
[2024-08-15 16:06] Device: cuda:0 NVIDIA A10G : cudaMallocAsync
[2024-08-15 16:06] ------------------------------------------
[2024-08-15 16:06] Comfyroll Studio v1.76 :  175 Nodes Loaded
[2024-08-15 16:06] ------------------------------------------
[2024-08-15 16:06] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[2024-08-15 16:06] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[2024-08-15 16:06] ------------------------------------------
[2024-08-15 16:06] ### Loading: ComfyUI-Impact-Pack (V6.2)
[2024-08-15 16:06] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[2024-08-15 16:06] [Impact Pack] Wildcards loading done.
[2024-08-15 16:06] 
[2024-08-15 16:06] [rgthree] Loaded 43 fantastic nodes.
[2024-08-15 16:06] [rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.
[2024-08-15 16:06] 
[2024-08-15 16:06] [comfy_mtb] | INFO -> loaded 86 nodes successfuly
[2024-08-15 16:06] WAS Node Suite: OpenCV Python FFMPEG support is enabled
[2024-08-15 16:06] WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
[2024-08-15 16:06] WAS Node Suite: Finished. Loaded 218 nodes successfully.
[2024-08-15 16:06] 
        "Life is 10% what happens to us and 90% how we react to it." - Charles R. Swindoll
[2024-08-15 16:06] 
[2024-08-15 16:06] ### Loading: ComfyUI-Manager (V2.48.6)
[2024-08-15 16:06] ### ComfyUI Revision: 2544 [5960f946] | Released on '2024-08-15'
[2024-08-15 16:06] ### Loading: ComfyUI-Inspire-Pack (V0.83)
[2024-08-15 16:06] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-08-15 16:06] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-08-15 16:06] 
Unable to import `python_color_transfer.color_transfer`. Is `python-color-transfer` pip package installed? Skipping python color transfer nodes.

[2024-08-15 16:06] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-08-15 16:06] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-08-15 16:06] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-08-15 16:06] Traceback (most recent call last):
[2024-08-15 16:06]   File "/home/ubuntu/ComfyUI/custom_nodes/SaltAI/modules/node_importer.py", line 20, in import_module
    module = importlib.import_module(module_name, package=package_name)
[2024-08-15 16:06]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
[2024-08-15 16:06]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[2024-08-15 16:06]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[2024-08-15 16:06]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[2024-08-15 16:06]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[2024-08-15 16:06]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[2024-08-15 16:06]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2024-08-15 16:06]   File "/home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/image/website_screenshot.py", line 3, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
[2024-08-15 16:06] ModuleNotFoundError: No module named 'webdriver_manager'
[2024-08-15 16:06] [2024-08-15 16:06] Import times for Salt AI Node Modules:
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/api/stability_ai.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/masking/mask_convert.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/masking/mask_filters.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/masking/clipseg.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/masking/cropping.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/string/processing.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/io/input_output.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/utility/convert.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/utility/displayany.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/image/loaders.py
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI/nodes/image/image_processing.py
[2024-08-15 16:06]    0.1 seconds (IMPORT FAILED): image/website_screenshot.py
[2024-08-15 16:06] Error: No module named 'webdriver_manager'
[2024-08-15 16:06] 
Loaded Nodes:
SaltAIStableVideoDiffusion [Stable Video Diffusion], SaltMasksToImages [Masks to Tensors], SaltMaskDominantRegion [Dominant Mask Regions], SaltMaskMinorityRegion [Minority Mask Regions], SaltMaskArbitaryRegion [Arbitrary Mask Regions], SaltMaskSmoothRegion [Smooth Mask Regions], SaltMaskErodeRegion [Erode Mask Regions], SaltMaskSubtract [Subtract Mask Regions], SaltMaskAdd [Add Mask Regions], SaltMaskInvert [Invert Mask Regions], SaltMaskDilateRegion [Dilate Mask Regions], SaltMaskFillRegion [Fill Mask Regions], SaltMaskThresholdRegion [Threshold Mask Regions], SaltMaskFloorRegion [Floor Mask Regions], SaltMaskCeilingRegion [Ceiling Mask Regions], SaltMaskGaussianRegion [Gaussian Mask Regions], SaltMaskEdgeDetection [Edge Detect Mask Regions], SaltMaskGradientRegion [Gradient Filter Mask Regions], SaltMaskAdaptiveThresholdingRegion [Adaptive Threshold Mask Regions], SaltMaskHistogramEqualizationRegion [Hisogram Equalize Mask Regions], SaltMaskRegionLabeling [Label Mask Regions (RGB)], SaltMaskContourExtraction [Countour Mask Regions Extraction], SaltMaskBilateralFilter [Bilateral Filter Mask Regions], SaltMaskClipHardeningFilter [Clip Harden Region], SaltMaskSharpeningFilter [Sharpen Mask Regions], SaltMaskSkeletonization [Skeletonize Mask Regions], SaltMaskNoiseAddition [Add Noise to Mask Regions], SaltMaskRegionSplit [Split Regions], SaltCLIPSegLoader [CLIPSeg Model Loader (Salt)], SaltCLIPSegMasking [Batch Image CLIPSeg Masking], SaltCropImageLocation [Crop Batch Image Location], SaltImagePasteCrop [Crop Batch Image Paste], SaltMaskCropRegion [Mask Batch Crop Region], SaltBatchCropDataExtractor [Extract Crop Data from Batch], SAIStringRegexSearchReplace [Regex Search and Replace], SAIStringRegexSearchMatch [Regex Search and Match], SaltInput [Salt Workflow Input], SaltOutput [Salt Workflow Output], SaltInfo [Salt Workflow Info], SAIPrimitiveConverter [Primitive Value Converter], SaltDisplayAny [SaltDisplayAny], SaltLoadImageZip [Load Images from ZIP], SaltRGBAFromMask [Mask with Alpha (Transparency)], SaltImageBlendingModes [Composite Images]

Added LoRa extension format: .results
[2024-08-15 16:06] FizzleDorf Custom Nodes: Loaded
[2024-08-15 16:06] /home/ubuntu/.local/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)

[2024-08-15 16:06] Warn!: xFormers is available (Attention)
[2024-08-15 16:06] Warn!: Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CLIPSeg/__init__.py'

[2024-08-15 16:06] Warn!: Cannot import /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: '/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CLIPSeg/__init__.py'
[2024-08-15 16:06] ComfyUI-Portrait-Maker : ### : Check dependencies
[2024-08-15 16:06] ComfyUI-Portrait-Maker : /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Portrait-Maker/requirements.txt
[2024-08-15 16:06] ComfyUI-Portrait-Maker : aliyun-python-sdk-core-v3==2.13.10
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : opencv-python
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : tensorflow-cpu
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : tensorflow
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : onnx
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : onnxruntime
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : modelscope
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : scikit-image
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : matplotlib
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : insightface
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : diffusers==0.18.2
[2024-08-15 16:06] 
[2024-08-15 16:06] ComfyUI-Portrait-Maker : sentencepiece
[2024-08-15 16:06] PyTorch version 2.3.0+cu121 available.
[2024-08-15 16:06] TensorFlow version 2.13.0 available.
[2024-08-15 16:06] JAX version 0.4.25 available.
[2024-08-15 16:06] Start Setting weights
[2024-08-15 16:06] 
Import times for custom nodes:
[2024-08-15 16:06]    0.0 seconds (IMPORT FAILED): /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CLIPSeg
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/websocket_image_save.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/srl-nodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-SEGAttention
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ControlNet-LLLite-ComfyUI
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Logic
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/masquerade-nodes-comfyui
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Inpaint-CropAndStitch
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-post-processing-nodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/stability-ComfyUI-nodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CADS
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/sd-dynamic-thresholding
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/IPAdapter-ComfyUI
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfy-nodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-IC-Light
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfyui-lama-remover
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/clipseg.py
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_FizzNodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-InstantMesh
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_essentials
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyMath
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfyui_face_parsing
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-KJNodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfyui-dream-project
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ymc-node-suite-comfyui
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/rgthree-comfy
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/steerable-motion
[2024-08-15 16:06]    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_InstantID
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/easy-comfy-nodes
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/EasyAnimate
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfy_mtb
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/efficiency-nodes-comfyui
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
[2024-08-15 16:06]    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-08-15 16:06]    0.2 seconds: /home/ubuntu/ComfyUI/custom_nodes/SaltAI
[2024-08-15 16:06]    0.3 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
[2024-08-15 16:06]    0.5 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Allor
[2024-08-15 16:06]    0.7 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-MotionCtrl
[2024-08-15 16:06]    1.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle
[2024-08-15 16:06]    1.9 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Portrait-Maker
[2024-08-15 16:06]    1.9 seconds: /home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui
[2024-08-15 16:06]    3.8 seconds: /home/ubuntu/ComfyUI/custom_nodes/deforum-comfy-nodes
[2024-08-15 16:06]    4.5 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-3D-Pack
[2024-08-15 16:06]    8.6 seconds: /home/ubuntu/ComfyUI/custom_nodes/facedetailer
[2024-08-15 16:06] 
[2024-08-15 16:06] Starting server

[2024-08-15 16:06] To see the GUI go to: http://0.0.0.0:8188
[2024-08-15 16:07] FETCH DATA from: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
[2024-08-15 16:07] # 😺dzNodes: LayerStyle -> Warning: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/custom_size.ini not found, use default size. 
[2024-08-15 16:07] # 😺dzNodes: LayerStyle -> Warning: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/custom_size.ini not found, use default size. 
[2024-08-15 16:07] # 😺dzNodes: LayerStyle -> Warning: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/custom_size.ini not found, use default size. 
[2024-08-15 16:07] # 😺dzNodes: LayerStyle -> Warning: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_LayerStyle/custom_size.ini not found, use default size. 
[2024-08-15 16:07] got prompt
[2024-08-15 16:07] !!! Exception during processing !!! map_node_over_list() got an unexpected keyword argument 'execution_block_cb'
[2024-08-15 16:07] Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
TypeError: map_node_over_list() got an unexpected keyword argument 'execution_block_cb'

[2024-08-15 16:07] Prompt executed in 0.00 seconds
[2024-08-15 16:07] got prompt
[2024-08-15 16:07] !!! Exception during processing !!! map_node_over_list() got an unexpected keyword argument 'execution_block_cb'
[2024-08-15 16:07] Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
TypeError: map_node_over_list() got an unexpected keyword argument 'execution_block_cb'

[2024-08-15 16:07] Prompt executed in 0.00 seconds
[2024-08-15 16:07] got prompt
[2024-08-15 16:07] !!! Exception during processing !!! map_node_over_list() got an unexpected keyword argument 'execution_block_cb'
[2024-08-15 16:07] Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
TypeError: map_node_over_list() got an unexpected keyword argument 'execution_block_cb'

[2024-08-15 16:07] Prompt executed in 0.00 seconds
[2024-08-15 16:08] got prompt
[2024-08-15 16:08] !!! Exception during processing !!! map_node_over_list() got an unexpected keyword argument 'execution_block_cb'
[2024-08-15 16:08] Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
TypeError: map_node_over_list() got an unexpected keyword argument 'execution_block_cb'

[2024-08-15 16:08] Prompt executed in 0.00 seconds
[2024-08-15 16:12] got prompt
[2024-08-15 16:12] !!! Exception during processing !!! map_node_over_list() got an unexpected keyword argument 'execution_block_cb'
[2024-08-15 16:12] Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
TypeError: map_node_over_list() got an unexpected keyword argument 'execution_block_cb'

[2024-08-15 16:12] Prompt executed in 0.00 seconds
```

### Other

The issue does not happen on the commit before merging the new execution model
[Try to fix SDXL OOM issue on some configurations.](https://github.com/comfyanonymous/ComfyUI/commit/0f9c2a78224ce3179c773fe3af63722f438b0613)

**Comment by comfyanonymous** [comment]
You probably have a custom node that patches execution.py, I'm not sure which one it is though.

**Comment by comfyanonymous** [comment]
Oh, it's deforum:
```
[2024-08-15 16:06] [deforum] Execution HiJack Active
```

https://github.com/XmYx/deforum-comfy-nodes/blob/main/deforum_nodes/exec_hijack.py

**Comment by sanguivore-easyco** [comment]
> Oh, it's deforum:
> 
> ```
> [2024-08-15 16:06] [deforum] Execution HiJack Active
> ```
> 
> https://github.com/XmYx/deforum-comfy-nodes/blob/main/deforum_nodes/exec_hijack.py

Ah, that makes sense. I don't even use it, so I'll just remove that one. Thanks! (notably I see `rgthree` deciding not to hijack execution in the logs 🎉 )

**Comment by sanguivore-easyco** [comment]
Removing the deforum nodes fixed the issue, thanks!

**Comment by wudideasdf** [comment]
same error, but i still need it  ·····

**Comment by ltdrdata** [comment]
> same error, but i still need it ·····

This issue should be addressed at the corresponding node.
Keep an eye on the following issues.
https://github.com/XmYx/deforum-comfy-nodes/issues/48

**Comment by wudideasdf** [comment]
> > same error, but i still need it ·····同样的错误，但我仍然需要它......
> 
> This issue should be addressed at the corresponding node.这个问题应该在相应的节点上解决。 Keep an eye on the following issues.请密切关注以下问题。 [XmYx/deforum-comfy-nodes#48](https://github.com/XmYx/deforum-comfy-nodes/issues/48)

Thank you, I temporarily disabled the Deforum node,

**Comment by Jaffa421** [comment]
Still getting "map_node_over_list() got an unexpected keyword argument 'execution_block_cb'" error
with basic Load Image from Directory node and Video Combine node, no deforum nodes.

**Comment by nhuyle1912** [comment]
"I'm getting this error when running to the 'depth anything' step, I don't know how to fix it. I hope someone can help me. Thank you very much."

DepthAnythingPreprocessor:

Allocation on device

File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything.py", line 23, in execute
out = common_annotator_call(model, image, resolution=resolution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\__init__.py", line 63, in __call__
depth = self.model(image)
^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\depth_anything\dpt.py", line 157, in forward
features = self.pretrained.get_intermediate_layers(x, 4, return_class_token=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\vision_transformer.py", line 308, in get_intermediate_layers
outputs = self._get_intermediate_layers_not_chunked(x, n)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\vision_transformer.py", line 277, in _get_intermediate_layers_not_chunked
x = blk(x)
^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\dinov2\layers\block.py", line 240, in forward
return super().forward(x_or_x_list)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\dinov2\layers\block.py", line 98, in forward
x = x + attn_residual_func(x)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\dinov2\layers\block.py", line 77, in attn_residual_func
return self.ls1(self.attn(self.norm1(x)))
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\dinov2\layers\attention.py", line 63, in forward
return super().forward(x)
^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\dinov2\layers\attention.py", line 50, in forward
attn = attn.softmax(dim=-1)
