### ISSUE TITLE
[Bug]: TypeError in KSampler

### ISSUE THREAD

**Issue by jorgealbr** [comfyanonymous/ComfyUI#4741]
# ComfyUI Error Report
## Error Details
- **Node Type:** KSampler
- **Exception Type:** TypeError
- **Exception Message:** calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
## Stack Trace
```
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)

  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)

  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)

  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)

  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)

  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)

```
## System Information
- **ComfyUI Version:** v0.1.3-20-gc90459e
- **Arguments:** main.py --front-end-version Comfy-Org/ComfyUI_frontend@0.0.2
- **OS:** posix
- **Python Version:** 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce MX130 : native
  - **Type:** cuda
  - **VRAM Total:** 2100232192
  - **VRAM Free:** 1288501760
  - **Torch VRAM Total:** 903872512
  - **Torch VRAM Free:** 127662592

## Logs
```
2024-09-01 20:54:57,202 - root - INFO - Total VRAM 2003 MB, total RAM 23833 MB
2024-09-01 20:54:57,203 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-01 20:54:57,203 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-01 20:54:57,203 - root - INFO - Device: cuda:0 NVIDIA GeForce MX130 : native
2024-09-01 20:54:57,964 - root - INFO - Using pytorch cross attention
2024-09-01 20:54:59,628 - root - ERROR - Failed to initialize frontend: Version 0.0.2 not found in releases
2024-09-01 20:54:59,629 - root - INFO - Falling back to the default frontend.
2024-09-01 20:54:59,629 - root - INFO - [Prompt Server] web root: /home/jorge/ComfyUI/web
2024-09-01 20:55:00,006 - root - INFO - Total VRAM 2003 MB, total RAM 23833 MB
2024-09-01 20:55:00,006 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-01 20:55:00,006 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-01 20:55:00,007 - root - INFO - Device: cuda:0 NVIDIA GeForce MX130 : native
2024-09-01 20:55:00,091 - root - INFO - 
Import times for custom nodes:
2024-09-01 20:55:00,092 - root - INFO -    0.0 seconds: /home/jorge/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-01 20:55:00,092 - root - INFO -    0.0 seconds: /home/jorge/ComfyUI/custom_nodes/ComfyUI-Video-Matting
2024-09-01 20:55:00,092 - root - INFO -    0.0 seconds: /home/jorge/ComfyUI/custom_nodes/ComfyUI-IC-Light
2024-09-01 20:55:00,092 - root - INFO -    0.0 seconds: /home/jorge/ComfyUI/custom_nodes/ComfyUI_essentials
2024-09-01 20:55:00,092 - root - INFO -    0.0 seconds: /home/jorge/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-01 20:55:00,092 - root - INFO -    0.1 seconds: /home/jorge/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-09-01 20:55:00,092 - root - INFO - 
2024-09-01 20:55:00,098 - root - INFO - Starting server

2024-09-01 20:55:00,098 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-01 20:56:20,042 - root - INFO - got prompt
2024-09-01 20:56:20,156 - root - INFO - model weight dtype torch.bfloat16, manual cast: torch.float32
2024-09-01 20:56:20,176 - root - INFO - model_type EPS
2024-09-01 20:56:20,801 - root - INFO - Using pytorch attention in VAE
2024-09-01 20:56:20,802 - root - INFO - Using pytorch attention in VAE
2024-09-01 20:56:20,922 - root - INFO - Requested to load SD1ClipModel
2024-09-01 20:56:20,922 - root - INFO - Loading 1 new model
2024-09-01 20:56:20,928 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-09-01 20:56:23,928 - root - INFO - Requested to load AutoencoderKL
2024-09-01 20:56:23,928 - root - INFO - Loading 1 new model
2024-09-01 20:56:24,070 - root - INFO - loaded completely 0.0 319.11416244506836 True
2024-09-01 20:56:27,172 - root - INFO - Unloading models for lowram load.
2024-09-01 20:56:27,344 - root - INFO - 0 models unloaded.
2024-09-01 20:56:30,314 - root - INFO - Requested to load BaseModel
2024-09-01 20:56:30,314 - root - INFO - Loading 1 new model
2024-09-01 20:56:31,435 - root - WARNING - WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
2024-09-01 20:56:31,439 - root - INFO - loaded partially 740.26201171875 740.261848449707 635
2024-09-01 20:56:31,480 - root - ERROR - !!! Exception during processing !!! calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
2024-09-01 20:56:31,482 - root - ERROR - Traceback (most recent call last):
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)
  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

2024-09-01 20:56:31,482 - root - INFO - Prompt executed in 11.43 seconds
2024-09-01 20:58:41,604 - root - INFO - got prompt
2024-09-01 20:58:41,651 - root - INFO - Unloading models for lowram load.
2024-09-01 20:58:41,660 - root - INFO - 0 models unloaded.
2024-09-01 20:58:41,680 - root - ERROR - !!! Exception during processing !!! calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
2024-09-01 20:58:41,681 - root - ERROR - Traceback (most recent call last):
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)
  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

2024-09-01 20:58:41,681 - root - INFO - Prompt executed in 0.07 seconds
2024-09-01 20:59:53,665 - root - INFO - got prompt
2024-09-01 20:59:53,697 - root - INFO - Requested to load AutoencoderKL
2024-09-01 20:59:53,697 - root - INFO - Loading 1 new model
2024-09-01 20:59:54,036 - root - INFO - loaded completely 0.0 319.11416244506836 True
2024-09-01 20:59:59,715 - root - INFO - Prompt executed in 6.04 seconds
2024-09-01 21:00:11,660 - root - INFO - got prompt
2024-09-01 21:00:11,695 - root - INFO - Prompt executed in 0.03 seconds
2024-09-01 21:00:47,991 - root - INFO - got prompt
2024-09-01 21:00:48,033 - root - INFO - Prompt executed in 0.03 seconds
2024-09-01 21:01:07,454 - root - INFO - got prompt
2024-09-01 21:01:07,484 - root - INFO - Requested to load BaseModel
2024-09-01 21:01:07,484 - root - INFO - Loading 1 new model
2024-09-01 21:01:08,723 - root - WARNING - WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
2024-09-01 21:01:08,727 - root - INFO - loaded partially 740.26201171875 740.261848449707 635
2024-09-01 21:01:08,743 - root - ERROR - !!! Exception during processing !!! calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
2024-09-01 21:01:08,743 - root - ERROR - Traceback (most recent call last):
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)
  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

2024-09-01 21:01:08,744 - root - INFO - Prompt executed in 1.28 seconds
2024-09-01 21:01:39,290 - root - INFO - got prompt
2024-09-01 21:01:39,341 - root - INFO - Unloading models for lowram load.
2024-09-01 21:01:39,346 - root - INFO - 0 models unloaded.
2024-09-01 21:01:39,367 - root - ERROR - !!! Exception during processing !!! calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
2024-09-01 21:01:39,367 - root - ERROR - Traceback (most recent call last):
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 144, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)
  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

2024-09-01 21:01:39,368 - root - INFO - Prompt executed in 0.07 seconds
2024-09-01 21:02:21,905 - root - INFO - got prompt
2024-09-01 21:02:21,960 - root - INFO - loaded partially 740.2394287109375 740.2392654418945 2
2024-09-01 21:02:21,983 - root - ERROR - !!! Exception during processing !!! calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
2024-09-01 21:02:21,984 - root - ERROR - Traceback (most recent call last):
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)
  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

2024-09-01 21:02:21,984 - root - INFO - Prompt executed in 0.07 seconds
2024-09-01 21:02:35,539 - root - INFO - got prompt
2024-09-01 21:02:35,588 - root - INFO - Unloading models for lowram load.
2024-09-01 21:02:35,594 - root - INFO - 0 models unloaded.
2024-09-01 21:02:35,617 - root - ERROR - !!! Exception during processing !!! calculate_weight() got an unexpected keyword argument 'intermediate_dtype'
2024-09-01 21:02:35,618 - root - ERROR - Traceback (most recent call last):
  File "/home/jorge/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jorge/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jorge/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jorge/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/jorge/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/jorge/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/k_diffusion/sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/jorge/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/jorge/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 843, in forward
    emb = self.time_embed(t_emb)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jorge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 71, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
  File "/home/jorge/ComfyUI/comfy/ops.py", line 52, in cast_bias_weight
    bias = s.bias_function(bias)
  File "/home/jorge/ComfyUI/comfy/model_patcher.py", line 91, in __call__
    return comfy.lora.calculate_weight(self.patches[self.key], weight, self.key, intermediate_dtype=weight.dtype)
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

2024-09-01 21:02:35,618 - root - INFO - Prompt executed in 0.07 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":48,"last_link_id":171,"nodes":[{"id":20,"type":"VAEEncode","pos":{"0":1250,"1":760,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":46},"flags":{},"order":12,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":168,"slot_index":0},{"name":"vae","type":"VAE","link":150,"slot_index":1}],"outputs":[{"name":"LATENT","type":"LATENT","links":[123],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEEncode"}},{"id":39,"type":"ImageResize+","pos":{"0":-220,"1":1030,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":218},"flags":{},"order":7,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":144}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[164],"slot_index":0,"shape":3},{"name":"width","type":"INT","links":[169],"slot_index":1,"shape":3},{"name":"height","type":"INT","links":[170],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"ImageResize+"},"widgets_values":[512,512,"nearest","stretch","always",0]},{"id":7,"type":"VAEDecode","pos":{"0":1910,"1":380,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":46},"flags":{},"order":14,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":77},{"name":"vae","type":"VAE","link":171,"slot_index":1}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[134],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEDecode"}},{"id":47,"type":"CreateGradientFromCoords","pos":{"0":1050,"1":1030,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":178},"flags":{},"order":9,"mode":0,"inputs":[{"name":"coordinates","type":"STRING","link":165,"widget":{"name":"coordinates"}},{"name":"frame_width","type":"INT","link":169,"widget":{"name":"frame_width"}},{"name":"frame_height","type":"INT","link":170,"widget":{"name":"frame_height"}}],"outputs":[{"name":"image","type":"IMAGE","links":[166,168],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CreateGradientFromCoords"},"widgets_values":["",512,512,"orange","black",1]},{"id":48,"type":"PreviewImage","pos":{"0":1390,"1":930,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":247.72422790527344,"1":284.0975646972656},"flags":{},"order":11,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":166}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":36,"type":"PreviewImage","pos":{"0":1710,"1":830,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":377.3042297363281,"1":387.90838623046875},"flags":{},"order":15,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":134}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":44,"type":"ICLightConditioning","pos":{"0":1120,"1":510,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":342.5999755859375,"1":138},"flags":{},"order":10,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":157},{"name":"negative","type":"CONDITIONING","link":158},{"name":"vae","type":"VAE","link":159},{"name":"foreground","type":"LATENT","link":160,"slot_index":3},{"name":"opt_background","type":"LATENT","link":null}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[161],"slot_index":0,"shape":3},{"name":"negative","type":"CONDITIONING","links":[162],"slot_index":1,"shape":3},{"name":"empty_latent","type":"LATENT","links":null,"shape":3}],"properties":{"Node name for S&R":"ICLightConditioning"},"widgets_values":[0.18215]},{"id":5,"type":"CLIPTextEncode","pos":{"0":50,"1":780,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":354.0688781738281,"1":120.4896240234375},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[158],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["bad quality, bad picture"],"color":"#322","bgcolor":"#533"},{"id":45,"type":"VAEEncode","pos":{"0":834,"1":570,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":46},"flags":{},"order":8,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":164,"slot_index":0},{"name":"vae","type":"VAE","link":163,"slot_index":1}],"outputs":[{"name":"LATENT","type":"LATENT","links":[160],"shape":3}],"properties":{"Node name for S&R":"VAEEncode"}},{"id":40,"type":"Reroute","pos":{"0":967,"1":438,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":[75,26],"flags":{},"order":6,"mode":0,"inputs":[{"name":"","type":"*","link":148}],"outputs":[{"name":"VAE","type":"VAE","links":[150,159,163,171],"slot_index":0}],"properties":{"showOutputText":true,"horizontal":false}},{"id":46,"type":"SplineEditor","pos":{"0":468,"1":680,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":557,"1":942},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"mask","type":"MASK","links":null,"shape":3},{"name":"coord_str","type":"STRING","links":[165],"slot_index":1,"shape":3},{"name":"float","type":"FLOAT","links":null,"shape":3},{"name":"count","type":"INT","links":null,"shape":3},{"name":"normalized_str","type":"STRING","links":null,"shape":3}],"properties":{"Node name for S&R":"SplineEditor","points":"SplineEditor"},"widgets_values":["[{\"x\":0,\"y\":512},{\"x\":313.3174000000001,\"y\":180.08430000000004}]","[{\"x\":0,\"y\":512},{\"x\":313.3174133300781,\"y\":180.0843048095703}]",512,512,2,"path","cardinal",0.5,1,"list",0,1,null,null]},{"id":2,"type":"CheckpointLoaderSimple","pos":{"0":-350,"1":360,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":98},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[156],"slot_index":0,"shape":3},{"name":"CLIP","type":"CLIP","links":[4,5],"slot_index":1,"shape":3},{"name":"VAE","type":"VAE","links":[148],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["photon_v1.safetensors"]},{"id":4,"type":"CLIPTextEncode","pos":{"0":50,"1":530,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":400,"1":200},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":4}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[157],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["soft light, cinematic, masterpiece, best quality, photograph"],"color":"#232","bgcolor":"#353"},{"id":37,"type":"LoadAndApplyICLightUnet","pos":{"0":740,"1":350,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":381.3333740234375,"1":58},"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":156}],"outputs":[{"name":"MODEL","type":"MODEL","links":[137],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"LoadAndApplyICLightUnet"},"widgets_values":["IC-Light/iclight_sd15_fc.safetensors"]},{"id":9,"type":"LoadImage","pos":{"0":-340,"1":530,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":323.97991943359375,"1":427.6261901855469},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[144],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":[],"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Anciana Alegre antes de relight.png","image"]},{"id":19,"type":"KSampler","pos":{"0":1510,"1":381,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":262},"flags":{},"order":13,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":137,"slot_index":0},{"name":"positive","type":"CONDITIONING","link":161},{"name":"negative","type":"CONDITIONING","link":162,"slot_index":2},{"name":"latent_image","type":"LATENT","link":123}],"outputs":[{"name":"LATENT","type":"LATENT","links":[77],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[100361857014338,"fixed",25,2.05,"dpmpp_2m","karras",0.9]}],"links":[[4,2,1,4,0,"CLIP"],[5,2,1,5,0,"CLIP"],[77,19,0,7,0,"LATENT"],[123,20,0,19,3,"LATENT"],[134,7,0,36,0,"IMAGE"],[137,37,0,19,0,"MODEL"],[144,9,0,39,0,"IMAGE"],[148,2,2,40,0,"*"],[150,40,0,20,1,"VAE"],[156,2,0,37,0,"MODEL"],[157,4,0,44,0,"CONDITIONING"],[158,5,0,44,1,"CONDITIONING"],[159,40,0,44,2,"VAE"],[160,45,0,44,3,"LATENT"],[161,44,0,19,1,"CONDITIONING"],[162,44,1,19,2,"CONDITIONING"],[163,40,0,45,1,"VAE"],[164,39,0,45,0,"IMAGE"],[165,46,1,47,0,"STRING"],[166,47,0,48,0,"IMAGE"],[168,47,0,20,0,"IMAGE"],[169,39,1,47,1,"INT"],[170,39,2,47,2,"INT"],[171,40,0,7,1,"VAE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650711,"offset":[-718.5345871882001,-81.96873782580042]}},"version":0.4}
```

## Additional Context
I was traying to reproduce the workflow showed in https://github.com/kijai/ComfyUI-IC-Light. I had this message. I don't know if it is a bug on the latest version of comfyui or something else. Attached here is the workflow png that i was reproducing and the .json of my  workflow that gave me the error message. Thank you!!
[workflow_copia_del_origina.json](https://github.com/user-attachments/files/16831525/workflow_copia_del_origina.json)
 Thank you! 
![iclight_example_fc_controlled_gradient_01](https://github.com/user-attachments/assets/f92f042b-271a-4935-8b0c-49eae3c3a6ae)

**Comment by huchenlei** [comment]
Update your IC Light extension should solve the issue.

**Comment by yexiaohao03** [comment]
![Snipaste_2024-09-26_08-00-44](https://github.com/user-attachments/assets/036b9bfd-dcc8-4e00-9053-eb7eacf188ac)
i have the problem,too.

**Comment by memoabuser** [comment]
I have the same problem, too. I'm not very familiar with A.I. But I already tried to update comfy and IC-light extension and still having the same problem
![image](https://github.com/user-attachments/assets/c6c6eb06-0977-4ed1-8a63-8690030d18ff)

**Comment by ltdrdata** [comment]
There have been reports that the `intermediate_dtype` issue occurs when numpy is version 2 or higher. 
Please check your numpy version.

**Comment by noembryo** [comment]
numpy-1.25.2, same problem..

**Comment by hgfgwiai** [comment]
我是更新的节点解决的问题，你们可以试一试

**Comment by RogenDarell** [comment]
Any update on this issue?
