### ISSUE TITLE
After updating the latest version, I get an error，when I start running and can't open the page

### ISSUE THREAD

**Issue by dys2017** [comfyanonymous/ComfyUI#4854]
### Your question

Hi，After updating the latest version ， I get an error when I start running and can't open the page：
WARNING: request with non matching host and origin 127.0.0.1:8188 != 127.0.0.1, returning 403
The problem originates from 'server. py'
“def create_origin_only_middleware():"

I am a rookie and don't know how to fix it, I can only disable it to fix.
but the standalone build for Windows runs normally.

### Logs

WARNING: request with non matching host and origin 127.0.0.1:8188 != 127.0.0.1, returning 403

**Comment by comfyanonymous** [comment]
What's your web browser?

**Comment by dys2017** [comment]
> What's your web browser?

Google Chrome

**Comment by comfyanonymous** [comment]
which version?

**Comment by mcmonkey4eva** [comment]
`but the standalone build for Windows runs normally.` does your main install have anything unusual to it? relating to network config especially

The root issue here is for some reason the `Origin` header your browser is setting is missing the port, which shouldn't happen on normal setups.

**Comment by dys2017** [comment]
> which version?

Google Chrome
version： 128.0.6613.120

**Comment by dys2017** [comment]
> `but the standalone build for Windows runs normally.` does your main install have anything unusual to it? relating to network config especially
> 
> The root issue here is for some reason the `Origin` header your browser is setting is missing the port, which shouldn't happen on normal setups.

Is it related to my proxy server settings? ,I dont know，But even if I shut down the proxy server, it doesn't seem to work

**Comment by Amazon90** [comment]
![01](https://github.com/user-attachments/assets/016a921a-a472-4798-9708-b78e23209c90)
Do not synchronize the submission marked in the red box in the image above.

**Comment by niko2020** [comment]
Hi, same problem here, running un runpod, chrome.

**Comment by niko2020** [comment]
Anyone can point how to update without breaking my setup if I can't open ComfyUI in browser?
Cheers

**Comment by comfyanonymous** [comment]
Can you update and check if it's fixed now?

**Comment by niko2020** [comment]
Updated with git pull but still get the same error :

WARNING: request with non matching host and origin 100.6.17.129 != 552877mlln4e-3000.proxy.runpod.net, returning 403

---------------------
git pull
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 6), reused 9 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 2.49 KiB | 11.00 KiB/s, done.
From https://github.com/comfyanonymous/ComfyUI
   e3b0402b..e0b41243  master     -> origin/master
   ecd7435a..a3beceb1  rh-expand  -> origin/rh-expand
Updating e3b0402b..e0b41243
Fast-forward
 folder_paths.py | 10 +++++++++-
 server.py       |  7 ++++++-
 2 files changed, 15 insertions(+), 2 deletions(-)

**Comment by mcmonkey4eva** [comment]
ftr if you need a bypass, just launch with cli arg `--enable-cors-header` (rather than mucking with git too much). (But please don't just add that and go away, that arg shouldn't be needed so please keep helping test fixes!)

**Comment by dys2017** [comment]
> Can you update and check if it's fixed now?

yep, it has been fixed！！Cheers

**Comment by dys2017** [comment]
> ftr if you need a bypass, just launch with cli arg `--enable-cors-header` (rather than mucking with git too much). (But please don't just add that and go away, that arg shouldn't be needed so please keep helping test fixes!)

The recent update has fixed this issue！ ~~

**Comment by dys2017** [comment]
> ![01](https://private-user-images.githubusercontent.com/72290820/365543846-016a921a-a472-4798-9708-b78e23209c90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Njg4MzQsIm5iZiI6MTcyNTg2ODUzNCwicGF0aCI6Ii83MjI5MDgyMC8zNjU1NDM4NDYtMDE2YTkyMWEtYTQ3Mi00Nzk4LTk3MDgtYjc4ZTIzMjA5YzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA3NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YWE1ZTAxMWViMGNjZWI2NmZiMjIzZGM4YmE4M2FlNDgzYjhlMzhkNjZiY2NmYmY1MzVmMDliZjI0OTllM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQXUgf1NeGTsJ9Mn4faAqJzRKvJzQunszh1DPh2oGWQ) Do not synchronize the submission marked in the red box in the image above.

The recent update has fixed this issue！ ~~

**Comment by codingcn** [comment]
```
### ComfyUI Revision: 2669 [cd495536] | Released on '2024-09-09'

Starting server

To see the GUI go to: http://127.0.0.1:6006
WARNING: request with non matching host and origin u250013-b225-02cbf64f.westc.gpuhub.com != u250013-b225-02cbf64f.westc.gpuhub.com:8443, returning 403
WARNING: request with non matching host and origin u250013-b225-02cbf64f.westc.gpuhub.com != u250013-b225-02cbf64f.westc.gpuhub.com:8443, returning 403
```

The issue remains

**Comment by RONNYKHALIL** [comment]
+1

**Comment by RONNYKHALIL** [comment]
> @comfyanonymous
> 
> ```
> ### ComfyUI Revision: 2669 [cd495536] | Released on '2024-09-09'
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:6006
> WARNING: request with non matching host and origin u250013-b225-02cbf64f.westc.gpuhub.com != u250013-b225-02cbf64f.westc.gpuhub.com:8443, returning 403
> WARNING: request with non matching host and origin u250013-b225-02cbf64f.westc.gpuhub.com != u250013-b225-02cbf64f.westc.gpuhub.com:8443, returning 403
> ```
> 
> The issue remains

+1

**Comment by osyahbana** [comment]
Still same issue on my end (even on the latest update)
