### ISSUE TITLE
A recent update causes OOM

### ISSUE THREAD

**Issue by Djanghost** [comfyanonymous/ComfyUI#5000]
### Expected Behavior

Being able to generate

### Actual Behavior

Everything slows down in the Ksampler (Adv. Efficient) before the well-known “Out of memory” error message appears after a few minutes. I work with a RTX4090 24gbVRAM, 64gbRAM.

### Steps to Reproduce

Doing this update :
"Add model_options to load_controlnet function."
Commit : ad66f7c7d8c3dc2985f2fba4e40b503cb45be03a

### Debug Logs

```powershell
torch.cuda.OutOfMemoryError: Allocation on device 

2024-09-20 17:18:52,501 - root - ERROR - Got an OOM, unloading all loaded models.
2024-09-20 17:18:54,648 - root - INFO - Prompt executed in 362.24 seconds
```

### Other

I identified the bad update causing this memory problem. I did some git checkouts to check updates before this one and all work excepted this one :
"Add model_options to load_controlnet function."
Commit : ad66f7c7d8c3dc2985f2fba4e40b503cb45be03a

**Comment by lostinthewash** [comment]
I am getting this same error, running a 4060 TI 16 gbVRAM and 32 GB RAM. Do we just wait for someone to fix this and push a new update? Is there anything else we can do?

**Comment by Djanghost** [comment]
> I am getting this same error, running a 4060 TI 16 gbVRAM and 32 GB RAM. Do we just wait for someone to fix this and push a new update? Is there anything else we can do?

I ask myself the same questions. In the meantime, I only update my custom nodes, not ComfyUI. I've saved a backup of my portable version just in case. Sometimes I test a Comfy update to see if the problem has been solved, but it hasn't happened yet. Given the number of errors following the latest Comfy updates, I don't think this problem is a priority for the devs until more people report it...

**Comment by comfyanonymous** [comment]
This should be fixed in the latest commit.

**Comment by Djanghost** [comment]
I confirm, thank you!

**Comment by lostinthewash** [comment]
After running the update ComfyUI and Python tool, this error still happens for me. Stops the process around 70%. Is the updating tool not pulling the latest commit?

**Comment by Djanghost** [comment]
Did you try to update via the manager in ComfyUI ?

**Comment by lostinthewash** [comment]
No, I ran the .bat files in the base "updates" folder. I just tried the "Check Update" and "Check Missing" in Manager. Both gave "no results". Attached is the system logs of the error, if that helps. 
[OOM_recentUpdate_sept22.txt](https://github.com/user-attachments/files/17089973/OOM_recentUpdate_sept22.txt)

**Comment by lostinthewash** [comment]
Hold up. This might be a case of user error on my part. Trying a few things and will report back. Thanks for all the help so far!

**Comment by lostinthewash** [comment]
Nope. Updating via "Update All", "Update ComfyUI", and "Fetch Updates" did not work, even after restarting the local server. Hummm . . .
![Screenshot 2024-09-22 101417](https://github.com/user-attachments/assets/3dcccecf-d506-451f-8b81-2b3f7460dd91)

**Comment by lostinthewash** [comment]
Sorry. Apparently it was running two instances of ComfyUI at once? Weird. I am now at 70% done overall and 6% done on the CogVideoSampler part (the part where it makes all the frames, I think). Thanks for the help! Keep up the good work, heroes.

**Comment by kdxwyg** [comment]
The same workflow, which was able to run well last week, is now directly bursting vram

**Comment by ffdown** [comment]
+1

**Comment by Pinkmoth419** [comment]
can confirm

**Comment by abarth1012** [comment]
Someone have news about this?
