### ISSUE TITLE
headdim should be in [64, 96, 128].

### ISSUE THREAD

**Issue by liaceboy** [comfyanonymous/ComfyUI#6733]
# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** KSampler
- **Exception Type:** AssertionError
- **Exception Message:** headdim should be in [64, 96, 128].
## Stack Trace
```
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\nodes.py", line 1503, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\nodes.py", line 1470, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\Comfyui-StableSR\nodes.py", line 69, in hook_sample
    return original_sample(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 117, in KSampler_sample
    return orig_fn(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 1013, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 135, in sample
    return orig_fn(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 911, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 897, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 866, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 850, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 100, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 707, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\k_diffusion\sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 379, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 832, in __call__
    return self.predict_noise(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 835, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 175, in sampling_function
    out = orig_fn(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 359, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 195, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 308, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\model_base.py", line 129, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\model_base.py", line 158, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 71, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 831, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 873, in _forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 767, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 254, in forward
    return func(self, x, context, transformer_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\attension_sharing.py", line 252, in forward
    return func(self, x, context, transformer_options)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 654, in forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 548, in forward
    out = optimized_attention(q, k, v, self.heads, attn_precision=self.attn_precision)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 474, in attention_sage
    out = sageattn(q, k, v, attn_mask=mask, is_causal=False, tensor_layout=tensor_layout)

  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\sageattention\core.py", line 82, in sageattn
    assert headdim in [64, 96, 128], "headdim should be in [64, 96, 128]."

```
## System Information
- **ComfyUI Version:** v0.3.9
- **Arguments:** D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\main.py --auto-launch --preview-method auto --use-sage-attention --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 22022971100
  - **Torch VRAM Total:** 2013265920
  - **Torch VRAM Free:** 13360860

## Logs
```
2025-02-07T12:10:22.602763 - []2025-02-07T12:10:22.602763 - 
2025-02-07T12:10:24.693096 - []2025-02-07T12:10:24.693096 - 
2025-02-07T12:10:26.458255 - []2025-02-07T12:10:26.459255 - 
2025-02-07T12:10:28.814343 - []2025-02-07T12:10:28.814343 - 
2025-02-07T12:10:30.904672 - []2025-02-07T12:10:30.904672 - 
2025-02-07T12:10:32.509485 - []2025-02-07T12:10:32.509485 - 
2025-02-07T12:10:34.964828 - []2025-02-07T12:10:34.964828 - 
2025-02-07T12:10:37.031536 - []2025-02-07T12:10:37.031536 - 
2025-02-07T12:10:38.614093 - []2025-02-07T12:10:38.614093 - 
2025-02-07T12:10:41.098781 - []2025-02-07T12:10:41.098781 - 
2025-02-07T12:10:43.099095 - []2025-02-07T12:10:43.099095 - 
2025-02-07T12:10:44.649945 - []2025-02-07T12:10:44.649945 - 
2025-02-07T12:10:47.146186 - []2025-02-07T12:10:47.146186 - 
2025-02-07T12:10:49.179872 - []2025-02-07T12:10:49.179872 - 
2025-02-07T12:10:50.695795 - []2025-02-07T12:10:50.695795 - 
2025-02-07T12:10:53.214338 - []2025-02-07T12:10:53.214338 - 
2025-02-07T12:10:55.320739 - []2025-02-07T12:10:55.320739 - 
2025-02-07T12:10:56.756822 - []2025-02-07T12:10:56.756822 - 
2025-02-07T12:10:59.342280 - []2025-02-07T12:10:59.342280 - 
2025-02-07T12:11:01.411776 - []2025-02-07T12:11:01.411776 - 
2025-02-07T12:11:02.781696 - []2025-02-07T12:11:02.781696 - 
2025-02-07T12:11:05.470216 - []2025-02-07T12:11:05.470216 - 
2025-02-07T12:11:07.499083 - []2025-02-07T12:11:07.499083 - 
2025-02-07T12:11:08.847130 - []2025-02-07T12:11:08.847130 - 
2025-02-07T12:11:11.546218 - []2025-02-07T12:11:11.546218 - 
2025-02-07T12:11:13.591274 - []2025-02-07T12:11:13.591274 - 
2025-02-07T12:11:14.841913 - []2025-02-07T12:11:14.841913 - 
2025-02-07T12:11:17.608966 - []2025-02-07T12:11:17.608966 - 
2025-02-07T12:11:19.635971 - []2025-02-07T12:11:19.635971 - 
2025-02-07T12:11:20.847852 - []2025-02-07T12:11:20.847852 - 
2025-02-07T12:11:23.604560 - []2025-02-07T12:11:23.604560 - 
2025-02-07T12:11:25.659263 - []2025-02-07T12:11:25.659263 - 
2025-02-07T12:11:26.877122 - []2025-02-07T12:11:26.877122 - 
2025-02-07T12:11:29.682101 - []2025-02-07T12:11:29.682101 - 
2025-02-07T12:11:31.709104 - []2025-02-07T12:11:31.709104 - 
2025-02-07T12:11:32.920192 - []2025-02-07T12:11:32.920192 - 
2025-02-07T12:11:35.770089 - []2025-02-07T12:11:35.770089 - 
2025-02-07T12:11:37.777655 - []2025-02-07T12:11:37.777655 - 
2025-02-07T12:11:38.968131 - []2025-02-07T12:11:38.968131 - 
2025-02-07T12:11:41.800529 - []2025-02-07T12:11:41.800529 - 
2025-02-07T12:11:43.777613 - []2025-02-07T12:11:43.778612 - 
2025-02-07T12:11:44.981603 - []2025-02-07T12:11:44.981603 - 
2025-02-07T12:11:47.894338 - []2025-02-07T12:11:47.894338 - 
2025-02-07T12:11:49.906431 - []2025-02-07T12:11:49.906431 - 
2025-02-07T12:11:50.971541 - []2025-02-07T12:11:50.972541 - 
2025-02-07T12:11:52.896977 - []2025-02-07T12:11:52.896977 - 
2025-02-07T12:11:54.907070 - []2025-02-07T12:11:54.907070 - 
2025-02-07T12:11:57.433793 - []2025-02-07T12:11:57.433793 - 
2025-02-07T12:11:57.496895 - []2025-02-07T12:11:57.496895 - 
2025-02-07T12:11:59.440709 - []2025-02-07T12:11:59.440709 - 
2025-02-07T12:12:01.410616 - []2025-02-07T12:12:01.410616 - 
2025-02-07T12:12:04.001427 - []2025-02-07T12:12:04.001427 - 
2025-02-07T12:12:04.073400 - []2025-02-07T12:12:04.073400 - 
2025-02-07T12:12:06.027167 - []2025-02-07T12:12:06.027167 - 
2025-02-07T12:12:08.056203 - []2025-02-07T12:12:08.056203 - 
2025-02-07T12:12:10.619271 - []2025-02-07T12:12:10.619271 - 
2025-02-07T12:12:10.623271 - []2025-02-07T12:12:10.623271 - 
2025-02-07T12:12:12.680902 - []2025-02-07T12:12:12.680902 - 
2025-02-07T12:12:14.763940 - []2025-02-07T12:12:14.763940 - 
2025-02-07T12:12:17.218672 - []2025-02-07T12:12:17.218672 - 
2025-02-07T12:12:17.366367 - []2025-02-07T12:12:17.366367 - 
2025-02-07T12:12:19.427609 - []2025-02-07T12:12:19.427609 - 
2025-02-07T12:12:21.488729 - []2025-02-07T12:12:21.488729 - 
2025-02-07T12:12:23.272688 - []2025-02-07T12:12:23.272688 - 
2025-02-07T12:12:25.519050 - []2025-02-07T12:12:25.519050 - 
2025-02-07T12:12:27.531095 - []2025-02-07T12:12:27.531095 - 
2025-02-07T12:12:29.305127 - []2025-02-07T12:12:29.305127 - 
2025-02-07T12:12:31.538998 - []2025-02-07T12:12:31.539100 - 
2025-02-07T12:12:33.612324 - []2025-02-07T12:12:33.612324 - 
2025-02-07T12:12:35.360495 - []2025-02-07T12:12:35.360495 - 
2025-02-07T12:12:37.633891 - []2025-02-07T12:12:37.633891 - 
2025-02-07T12:12:39.651433 - []2025-02-07T12:12:39.651433 - 
2025-02-07T12:12:41.364773 - []2025-02-07T12:12:41.364773 - 
2025-02-07T12:12:43.647908 - []2025-02-07T12:12:43.647908 - 
2025-02-07T12:12:45.653221 - []2025-02-07T12:12:45.653221 - 
2025-02-07T12:12:47.403867 - []2025-02-07T12:12:47.403867 - 
2025-02-07T12:12:49.645193 - []2025-02-07T12:12:49.645193 - 
2025-02-07T12:12:51.653048 - []2025-02-07T12:12:51.653048 - 
2025-02-07T12:12:53.415974 - []2025-02-07T12:12:53.415974 - 
2025-02-07T12:12:55.673102 - []2025-02-07T12:12:55.673102 - 
2025-02-07T12:12:57.700926 - []2025-02-07T12:12:57.700926 - 
2025-02-07T12:12:59.442347 - []2025-02-07T12:12:59.442347 - 
2025-02-07T12:13:01.738007 - []2025-02-07T12:13:01.738007 - 
2025-02-07T12:13:03.852366 - []2025-02-07T12:13:03.852366 - 
2025-02-07T12:13:05.496073 - []2025-02-07T12:13:05.496073 - 
2025-02-07T12:13:07.987994 - []2025-02-07T12:13:07.987994 - 
2025-02-07T12:13:10.065244 - []2025-02-07T12:13:10.065244 - 
2025-02-07T12:13:11.601349 - []2025-02-07T12:13:11.601349 - 
2025-02-07T12:13:14.214015 - []2025-02-07T12:13:14.214015 - 
2025-02-07T12:13:16.329895 - []2025-02-07T12:13:16.329895 - 
2025-02-07T12:13:17.656838 - []2025-02-07T12:13:17.656838 - 
2025-02-07T12:13:20.442270 - []2025-02-07T12:13:20.442270 - 
2025-02-07T12:13:22.542559 - []2025-02-07T12:13:22.542559 - 
2025-02-07T12:13:23.702797 - []2025-02-07T12:13:23.702797 - 
2025-02-07T12:13:26.567852 - []2025-02-07T12:13:26.567852 - 
2025-02-07T12:13:28.609840 - []2025-02-07T12:13:28.609840 - 
2025-02-07T12:13:29.756512 - []2025-02-07T12:13:29.756512 - 
2025-02-07T12:13:32.603227 - []2025-02-07T12:13:32.603227 - 
2025-02-07T12:13:34.596802 - []2025-02-07T12:13:34.596802 - 
2025-02-07T12:13:35.746687 - []2025-02-07T12:13:35.746687 - 
2025-02-07T12:13:38.618903 - []2025-02-07T12:13:38.618903 - 
2025-02-07T12:13:40.608867 - []2025-02-07T12:13:40.608867 - 
2025-02-07T12:13:41.739108 - []2025-02-07T12:13:41.739108 - 
2025-02-07T12:13:44.644914 - []2025-02-07T12:13:44.644914 - 
2025-02-07T12:13:46.650597 - []2025-02-07T12:13:46.650597 - 
2025-02-07T12:13:47.743274 - []2025-02-07T12:13:47.743274 - 
2025-02-07T12:13:50.625136 - []2025-02-07T12:13:50.625136 - 
2025-02-07T12:13:52.708424 - []2025-02-07T12:13:52.708424 - 
2025-02-07T12:13:53.797960 - []2025-02-07T12:13:53.797960 - 
2025-02-07T12:13:56.708701 - []2025-02-07T12:13:56.708701 - 
2025-02-07T12:13:58.714478 - []2025-02-07T12:13:58.714478 - 
2025-02-07T12:13:59.811973 - []2025-02-07T12:13:59.811973 - 
2025-02-07T12:14:02.761110 - []2025-02-07T12:14:02.761110 - 
2025-02-07T12:14:04.792422 - []2025-02-07T12:14:04.792422 - 
2025-02-07T12:14:05.839335 - []2025-02-07T12:14:05.839335 - 
2025-02-07T12:14:07.813787 - []2025-02-07T12:14:07.813787 - 
2025-02-07T12:14:09.834192 - []2025-02-07T12:14:09.834192 - 
2025-02-07T12:14:12.349973 - []2025-02-07T12:14:12.349973 - []2025-02-07T12:14:12.349973 - 
2025-02-07T12:14:12.349973 - 
2025-02-07T12:14:14.375515 - []2025-02-07T12:14:14.375515 - 
2025-02-07T12:14:16.370872 - []2025-02-07T12:14:16.370872 - 
2025-02-07T12:14:18.850472 - []2025-02-07T12:14:18.850472 - 
2025-02-07T12:14:18.880492 - []2025-02-07T12:14:18.880492 - 
2025-02-07T12:14:20.864391 - []2025-02-07T12:14:20.864391 - 
2025-02-07T12:14:22.929889 - []2025-02-07T12:14:22.929889 - 
2025-02-07T12:14:25.403966 - []2025-02-07T12:14:25.403966 - 
2025-02-07T12:14:25.497218 - []2025-02-07T12:14:25.497218 - 
2025-02-07T12:14:26.436717 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2025-02-07T12:14:27.657192 - FETCH DATA from: D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Manager\extension-node-map.json2025-02-07T12:14:27.657192 - 2025-02-07T12:14:27.660262 -  [DONE]2025-02-07T12:14:27.660262 - 
2025-02-07T12:14:27.683735 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js2025-02-07T12:14:27.683735 - 
2025-02-07T12:14:27.691849 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css2025-02-07T12:14:27.691849 - 
2025-02-07T12:14:27.931302 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css2025-02-07T12:14:27.931302 - 
2025-02-07T12:14:27.933306 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css2025-02-07T12:14:27.933306 - 
2025-02-07T12:14:27.970640 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js2025-02-07T12:14:27.970640 - 
2025-02-07T12:14:27.974689 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js2025-02-07T12:14:27.974689 - 
2025-02-07T12:14:27.975689 - D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js2025-02-07T12:14:27.975689 - 
2025-02-07T12:14:27.976689 - []2025-02-07T12:14:27.976689 - 
2025-02-07T12:14:30.400914 - []2025-02-07T12:14:30.400914 - 
2025-02-07T12:14:30.925767 - []2025-02-07T12:14:30.925767 - 
2025-02-07T12:14:30.925767 - []2025-02-07T12:14:30.925767 - 
2025-02-07T12:14:31.002240 - send error: Cannot write to closing transport
2025-02-07T12:14:31.533403 - []2025-02-07T12:14:31.533403 - 
2025-02-07T12:14:34.448107 - []2025-02-07T12:14:34.448107 - 
2025-02-07T12:14:35.007478 - got prompt
2025-02-07T12:14:35.073262 - model weight dtype torch.float16, manual cast: None
2025-02-07T12:14:35.076774 - model_type EPS
2025-02-07T12:14:36.131787 - Using xformers attention in VAE
2025-02-07T12:14:36.132787 - Using xformers attention in VAE
2025-02-07T12:14:36.560403 - []2025-02-07T12:14:36.560403 - 
2025-02-07T12:14:36.797830 - Requested to load SD1ClipModel
2025-02-07T12:14:36.948067 - loaded completely 9.5367431640625e+25 235.84423828125 True
2025-02-07T12:14:37.295577 - Requested to load BaseModel
2025-02-07T12:14:37.647797 - loaded completely 9.5367431640625e+25 1639.406135559082 True
2025-02-07T12:14:37.872399 - !!! Exception during processing !!! headdim should be in [64, 96, 128].
2025-02-07T12:14:37.874422 - Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\nodes.py", line 1503, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\nodes.py", line 1470, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\Comfyui-StableSR\nodes.py", line 69, in hook_sample
    return original_sample(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 117, in KSampler_sample
    return orig_fn(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 1013, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 135, in sample
    return orig_fn(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 911, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 897, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 866, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 850, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 100, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 707, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\k_diffusion\sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 379, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 832, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 835, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 175, in sampling_function
    out = orig_fn(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 359, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 195, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\samplers.py", line 308, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\model_base.py", line 129, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\model_base.py", line 158, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 71, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 831, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 873, in _forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 767, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 254, in forward
    return func(self, x, context, transformer_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\attension_sharing.py", line 252, in forward
    return func(self, x, context, transformer_options)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 654, in forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 548, in forward
    out = optimized_attention(q, k, v, self.heads, attn_precision=self.attn_precision)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\comfy\ldm\modules\attention.py", line 474, in attention_sage
    out = sageattn(q, k, v, attn_mask=mask, is_causal=False, tensor_layout=tensor_layout)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\sageattention\core.py", line 82, in sageattn
    assert headdim in [64, 96, 128], "headdim should be in [64, 96, 128]."
AssertionError: headdim should be in [64, 96, 128].

2025-02-07T12:14:37.876933 - Prompt executed in 2.87 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":9,"last_link_id":9,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":["text, watermark"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"EmptyLatentImage","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":[512,512,1]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":4,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":6,"label":"负面条件"},{"name":"latent_image","type":"LATENT","link":2,"label":"Latent"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"KSampler","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":[439152487381515,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7,"label":"Latent"},{"name":"vae","type":"VAE","link":8,"label":"VAE"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"VAEDecode","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"SaveImage","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":["ComfyUI"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0,"label":"模型"},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1,"label":"CLIP"},{"name":"VAE","type":"VAE","links":[8],"slot_index":2,"label":"VAE"}],"properties":{"Node name for S&R":"CheckpointLoaderSimple","enableTabs":false,"tabWidth":65,"tabXOffset":10,"hasSecondTab":false,"secondTabText":"Send Back","secondTabOffset":80,"secondTabWidth":65},"widgets_values":["00\\anything-v5-PrtRE.safetensors"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7247295000000004,"offset":[638.6251515220497,242.78569659438438]},"ue_links":[]},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by liaceboy** [comment]
Uninstalling Xformers and SageTention has no effect

**Comment by liaceboy** [comment]
Issues that will occur after v0.3.6

**Comment by LukeG89** [comment]
Have your tried removing `--use-sage-attention` arg? I know that sage attention has problems with SD1.5

**Comment by kevinlv** [comment]
Me too. Now whenever using the SD1.5 model to generate images, the sampler will report this error.

**Comment by ltdrdata** [comment]
> Uninstalling Xformers and SageTention has no effect

If you have removed **sageattention**, the error message should have changed.  
Please check the error message again.  

If the same error message still appears, it means that **sageattention** was reinstalled or that it was removed in the wrong Python environment.

**Comment by ImNoobPleaseBeKind** [comment]
@liaceboy Did you fix the problem?
Can you please tell me how you managed to fix it?

**Comment by YuhowWang** [comment]
> [@liaceboy](https://github.com/liaceboy) Did you fix the problem? Can you please tell me how you managed to fix it?

What a coincidence, I have encountered this problem now. If you solve it, please teach me

**Comment by set-soft** [comment]
Ok, I get this when using sageattention, does it mean that we can't use sageattetion or that a node needs to be updated to support it?

**Comment by hesanta2** [comment]
I fixed the problem using the Path Sage Attention JS node with a disabled value.

![Image](https://github.com/user-attachments/assets/a8ec87c9-db64-4f76-a212-558c27cc7f84)

**Comment by ucn2081** [comment]
In my case, a temporary solution is to add the Kijai Patch Sage Attention KJ (PathchSageAttentionKJ) node between LoadModel and the ksampler in "disabled" mode. This way the workflow works correctly.

**Comment by nirurin** [comment]
> In my case, a temporary solution is to add the Kijai Patch Sage Attention KJ (PathchSageAttentionKJ) node between LoadModel and the ksampler in "disabled" mode. This way the workflow works correctly.

Unfortunately I have tried this, but it doesnt work. I still get the Unsupported head_dim 160 error.

**Comment by xlibfly** [comment]
> [@liaceboy](https://github.com/liaceboy)您解决这个问题了吗？ 您能告诉我您是如何解决这个问题的吗？

![Image](https://github.com/user-attachments/assets/5aa51107-cc09-4d94-bd7d-8cae18c34b66)
Cross-Attention use xFormers

**Comment by xlibfly** [comment]
> > [@liaceboy](https://github.com/liaceboy) Did you fix the problem? Can you please tell me how you managed to fix it?
> 
> What a coincidence, I have encountered this problem now. If you solve it, please teach me

Image
Cross-Attention use xFormers

**Comment by liaceboy** [comment]
> > > [@liaceboy](https://github.com/liaceboy) Did you fix the problem? Can you please tell me how you managed to fix it?[@liaceboy](https://github.com/liaceboy)你修复了这个问题吗？你能告诉我你是如何修复它的吗？
> > 
> > 
> > What a coincidence, I have encountered this problem now. If you solve it, please teach me好巧啊，我现在也遇到这个问题了，如果你解决了的话，请教教我
> 
> ![Image](https://github.com/user-attachments/assets/1dd90b9d-bd8d-44b8-9d39-d4b73df590c6)
> 
> Cross-Attention use xFormers交叉注意使用 xFormers

OK, thank you.

**Comment by Limbicnation** [comment]
Fixed it by running `pip uninstall sageattention`. Works now.

**Comment by wen26123** [comment]
> Fixed it by running `pip uninstall sageattention`. Works now.修复了通过运行 `pip uninstall sageattention` 。现在正常工作了。

Will there be problems after uninstallation

**Comment by wen26123** [comment]
> Fixed it by running `pip uninstall sageattention`. Works now.

D:\AI-SD\AI 2025\ComfyUI\python>pip uninstall sageattention
WARNING: Skipping sageattention as it is not installed.

I looked it up and realised that without installing sageattention, there was still this error. I had to switch to the xFormers method so that there was no error

**Comment by rrroddri** [comment]
I agree, please fix this issue, you have to be constantly restarting comfyui with the sage-attention flag to be able to use wan or flux at a decent speed and then remove the flag to use SD/SDXL

**Comment by KLL535** [comment]
XL works with the flag set. The problem is only with 1.5

**Comment by udappk** [comment]
> In my case, a temporary solution is to add the Kijai Patch Sage Attention KJ (PathchSageAttentionKJ) node between LoadModel and the ksampler in "disabled" mode. This way the workflow works correctly.

Thank You, This worked!!! I have sage attention enabled and still can use 1.5 using this method.. 🙏👏

**Comment by lxk61688** [comment]
It seems to be related to the 'diso' in the dependency. After I deleted 'diso', it was normal. This dependency was installed when I installed ComfyUI-3D-Pack

**Comment by Garrettlynch** [comment]
> > In my case, a temporary solution is to add the Kijai Patch Sage Attention KJ (PathchSageAttentionKJ) node between LoadModel and the ksampler in "disabled" mode. This way the workflow works correctly.
> 
> [@KLL535](https://github.com/KLL535) [@rrroddri](https://github.com/rrroddri) (if you still have this issue, try this method) Thank You, This worked!!! I have sage attention enabled and still can use 1.5 using this method.. 🙏👏

Tried this solution and I still get the same error.

**Comment by Garrettlynch** [comment]
> It seems to be related to the 'diso' in the dependency. After I deleted 'diso', it was normal. This dependency was installed when I installed ComfyUI-3D-Pack

lxk61688 is correct. Disable diso (https://github.com/SarahWeiii/diso) and IPadapter works. Below is the version of diso I had installed.

Name: diso Version: 0.1.4 Summary: Differentiable Iso-Surface Extraction Package Home-page: Author: Author-email: xiwei@ucsd.edu License: CC BY-NC 4.0 Location: /home/user/ComfyUI/venv/lib/python3.10/site-packages Requires: trimesh

**Comment by bolekcg** [comment]
Hello

Indeed .
@lxk61688 mention the truth - Removing diso helped 
But why is so? 
Pip doesn't show any conflicts 

Thanks.
