### ISSUE TITLE
Newest frontend update (partially) broke previews

### ISSUE THREAD

**Issue by NuclearWaste02** [comfyanonymous/ComfyUI#7134]
### Expected Behavior

When having previews enabled during ksampler generation, you used to be able to right click and "Open Image" on the finalized preview and view it in the web browser.

### Actual Behavior

Now it only renders previews at an extremely low quality. Clicking "Open Image", "Save Image" or "Copy Image" all don't work anymore and redirect to a blob image instead of the local file in the temp folder.

### Steps to Reproduce

Generate an image with a sampler that generates a realtime preview (e.g. KSampler Efficient). Once the image is generated, right click on the preview and hit "Open Image".

### Debug Logs

```powershell
N/A
```

### Other

Issue persists after latest update. [**This**](https://github.com/comfyanonymous/ComfyUI/pull/7119) merge seemed to cause this issue.

**Comment by huchenlei** [comment]
I am not sure if it is a frontend issue starting from v1.11 frontend. The preview quality in between v1.10 and v1.11 frontend are not significant to me. 

v1.10 preview

![Image](https://github.com/user-attachments/assets/8c75a6b6-78c9-42ab-b9f4-5433ecfbc8cd)

![Image](https://github.com/user-attachments/assets/c67001d4-ef27-4634-8370-67409c7d9c0e)

v1.11 preview

![Image](https://github.com/user-attachments/assets/493d4940-8737-4a5b-bfff-385c5ed20611)

![Image](https://github.com/user-attachments/assets/202e479f-d233-414b-8ba6-bb0e87e07270)

Is the high quality preview feature provided by a custom node? Can you try reproduce the issue with `--disable-all-custom-nodes` flag?

**Comment by LukeG89** [comment]
I've tested the issue, but I had no problem opening, copy-pasting and saving an image from Preview Image node.

This is frontend v1.11.8 and all custom nodes disabled:

https://github.com/user-attachments/assets/16a06b11-6a5e-4243-a9ce-a8989f21c2c7

**Comment by Vik71it** [comment]
I'm experiencing a similar problem with the standard ksampler node. I can't remember if the "old" behaviour was different with this node (until now I also used Efficiency Ksampler), but it seems right now that also changing the quality of the preview has no effect on the resulting preview of the KSampler node. I attach the result tested with the default workflow

Please let me know if there is some specifical test that could be useful to understand if it is a general problem or a custom node, and the behaviour of the standard ksampler is correct (also, for batches of file, it is shown only the preview for the first one)

![Image](https://github.com/user-attachments/assets/617849a6-610f-4de7-a237-600f60645daa)
![Image](https://github.com/user-attachments/assets/236f6fff-b9a7-4753-8531-a96021ce1106)

**Comment by christian-byrne** [comment]
> also, for batches of file, it is shown only the preview for the first one

Do you mean your expectation is an image grid of previews on the KSampler?

**Comment by Vik71it** [comment]
> Do you mean your expectation is an image grid of previews on the KSampler?

Yes, something similar to the "Preview Image" behaviour for a batch. But, since I was using a different KSampler node, not the standard one, I can't really say that this was the behaviour in previous releases.

**Comment by huchenlei** [comment]
The issue is found in the frontend: https://github.com/Comfy-Org/ComfyUI_frontend/issues/2944
Resolved in https://github.com/Comfy-Org/ComfyUI_frontend/pull/2952 (1.13.1 frontend). Once the fix is verified to work, the fix will be cherry-picked back to 1.12 and 1.11.

**Comment by christian-byrne** [comment]
The issue of not being able to right click KSampler previews, or them being a quality you did not expect?

**Comment by barbosaai** [comment]
> The issue of not being able to right click KSampler previews, or them being a quality you did not expect?

Still having the same issue. The previews stop if you go to a different tab, they won't update at all. If you click for it to run, and then go to another tab, when you come back to Comfy tab, the ksampler preview has not updated at all and still shows the previous one. The quality is fine. I think the problem is that when you use a preview, it never decodes inside the ksampler like it used it. If you select "VAE DECODE ONLY" as your preview method, you won't get live previews of it but it will decode inside the sampler and then you can right click and open in new tab and the image is full quality. If you go with TAESD or other preview method, it won't preview properly and will create a "blob" link when you try to open it in new tab to preview the image. It no longer decodes inside the sampler itself.

**Comment by christian-byrne** [comment]
Is this with the normal KSampler or a custom node? I can try to reproduce and investigate aagain. If you know a way to reproduce the issue, leaving the exact steps with details about the node, options, etc. is very helpful.
