### ISSUE TITLE
Commit broke loading of custom nodes - Resolved. Update to b779349b55e79aff81a98b752f5cb486c71812db

### ISSUE THREAD

**Issue by askmyteapot** [comfyanonymous/ComfyUI#7162]
### Expected Behavior

Load comfui - modules available in frontend

### Actual Behavior

Modules load in terminal, but arent available to frontend.

### Steps to Reproduce

Commit 6f8e766509c0c44ae2e04a79ab05a06e4467b51b is the breaking change. 

### Debug Logs

```powershell
python main.py --listen --port 8090 --disable-cuda-malloc --lowvram --use-sage-attention --fast
[START] Security scan
DEPRECATION: Loading egg at /home/media/ComfyUI/venv/lib/python3.12/site-packages/numba-0.61.0.dev0+360.g0f363d1b2-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-03-10 19:28:27.891
** Platform: Linux
** Python version: 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0]
** Python executable: /home/media/ComfyUI/venv/bin/python
** ComfyUI Path: /home/media/ComfyUI
** ComfyUI Base Folder Path: /home/media/ComfyUI
** User directory: /home/media/ComfyUI/user
** ComfyUI-Manager config path: /home/media/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /home/media/ComfyUI/user/comfyui.log
DEPRECATION: Loading egg at /home/media/ComfyUI/venv/lib/python3.12/site-packages/numba-0.61.0.dev0+360.g0f363d1b2-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /home/media/ComfyUI/venv/lib/python3.12/site-packages/numba-0.61.0.dev0+360.g0f363d1b2-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

Prestartup times for custom nodes:
   0.0 seconds: /home/media/ComfyUI/custom_nodes/rgthree-comfy
   2.1 seconds: /home/media/ComfyUI/custom_nodes/comfyui-manager

Checkpoint files will always be loaded safely.
/home/media/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py:792: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Total VRAM 24576 MB, total RAM 52210 MB
pytorch version: 2.7.0a0+git8cb8722
Enabled fp16 accumulation.
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
Using sage attention
ComfyUI version: 0.3.26
ComfyUI frontend version: 1.12.8
[Prompt Server] web root: /home/media/ComfyUI/venv/lib/python3.12/site-packages/comfyui_frontend_package/static
/home/media/ComfyUI/venv/lib/python3.12/site-packages/flash_attn/ops/fused_dense.py:29: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/home/media/ComfyUI/venv/lib/python3.12/site-packages/flash_attn/ops/fused_dense.py:70: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
/home/media/ComfyUI/venv/lib/python3.12/site-packages/flash_attn/ops/fused_dense.py:251: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/home/media/ComfyUI/venv/lib/python3.12/site-packages/flash_attn/ops/fused_dense.py:348: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
lm_eval is not installed, GPTQ may not be usable
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/home/media/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Every great dream begins with a dreamer." - Harriet Tubman


[rgthree-comfy] Loaded 42 magnificent nodes. 🎉

Total VRAM 24576 MB, total RAM 52210 MB
pytorch version: 2.7.0a0+git8cb8722
Enabled fp16 accumulation.
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
### Loading: ComfyUI-Manager (V3.30.3)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.26-3-g67c7184b | Released on '2025-03-10'
[/home/media/ComfyUI/custom_nodes/comfy_mtb] | INFO -> loaded 102 nodes successfuly
[/home/media/ComfyUI/custom_nodes/comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://0.0.0.0,:::8090/mtb if you want more information.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

Import times for custom nodes:
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-FloatRamp
   0.0 seconds: /home/media/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/media/ComfyUI/custom_nodes/teacache
   0.0 seconds: /home/media/ComfyUI/custom_nodes/wavespeed
   0.0 seconds: /home/media/ComfyUI/custom_nodes/comfyui_patches_ll
   0.0 seconds: /home/media/ComfyUI/custom_nodes/comfyui_essentials
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-LTXTricks
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/media/ComfyUI/custom_nodes/comfyui-browser
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-LTXVideo
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-MochiWrapper
   0.0 seconds: /home/media/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-GGUF
   0.0 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.0 seconds: /home/media/ComfyUI/custom_nodes/comfyui-hunyuanvideowrapper
   0.1 seconds: /home/media/ComfyUI/custom_nodes/comfy_mtb
   0.1 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-FluxTrainer
   0.1 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-Long-CLIP
   0.1 seconds: /home/media/ComfyUI/custom_nodes/comfyui-manager
   0.2 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.2 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper
   0.6 seconds: /home/media/ComfyUI/custom_nodes/ComfyUI-Florence2
   1.0 seconds: /home/media/ComfyUI/custom_nodes/was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8090
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
To see the GUI go to: http://[::]:8090
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH ComfyRegistry Data: 5/57
FETCH ComfyRegistry Data: 10/57
FETCH ComfyRegistry Data: 15/57
FETCH ComfyRegistry Data: 20/57
FETCH ComfyRegistry Data: 25/57
FETCH ComfyRegistry Data: 30/57
FETCH ComfyRegistry Data: 35/57
FETCH ComfyRegistry Data: 40/57
FETCH ComfyRegistry Data: 45/57
FETCH ComfyRegistry Data: 50/57
FETCH ComfyRegistry Data: 55/57
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
nightly_channel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
```

**Comment by KazutoEleros** [comment]
I thought I was going crazy but this exact issue just occurred for me too,
Installed some custom nodes and updated pre-existing nodes+ComfyUI, all nodes are importing without issue but the Managers UI doesn't show up in the UI when connecting to Comfy

**Comment by comfyanonymous** [comment]
Are you sure it's that commit?

**Comment by askmyteapot** [comment]
> Are you sure it's that commit?

Yes. If i checkout e1da98a14a21f5d4af31935832437b55e81d2399 (the previous commit) it fixes the problem

**Comment by Dwanvea** [comment]
All my custom nodes are broken as well, how do I switch to a previous commit?

**Comment by KazutoEleros** [comment]
> Are you sure it's that commit?

To be honest I am not sure, it was the current update that stopped working for me and when installing a fresh ComfyUI and installing the manager it continues to not display the manager so I came here to check only to see someone else had already posted the issue.
I was just expressing the issue was also occurring for me, showing the success of import but without the functionality to use the Manager in ComfyUI.
Tested on 3 browsers with cache resets, so highly doubtful it's a browser issue like previous user issues that had occurred.

**Comment by askmyteapot** [comment]
> All my custom nodes are broken as well, how do I switch to a previous commit?

```git checkout e1da98a14a21f5d4af31935832437b55e81d2399```

and to switch back to master once a fix is deployed 

```
git switch -
git pull --all 
```

**Comment by SRagy** [comment]
I found a bunch of issues too. Manager disappeared, rgthree muters vanished and video-helper-suite loader missing an upload button. I tried checking out an earlier comfyUI version but that actually didn't fix my issues. Will try again in case I somehow fucked that up.

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by askmyteapot** [comment]
> Should be fixed now.

Unfortunately not. It only fixed the manager. 
other nodes are still not loading correctly after pulling your change. 

![Image](https://github.com/user-attachments/assets/d926701a-d0fe-46fd-959d-97b304a1d958)

**Comment by Fr-Otaku** [comment]
Same for me, no manager at all, no more bookmark, or fast muter

![Image](https://github.com/user-attachments/assets/ca21b801-c1a4-460d-83ce-8e529e5d6020)

**Comment by askmyteapot** [comment]
@comfyanonymous 
Thanks for actioning the rollback so quickly. 

Will need to get some communication out to the community about that change and how it will impact modules going forward.

I'll close it in an hour or so.

**Comment by comfyanonymous** [comment]
I moved the change to a pull request that will be merged in a week or so to give people time to update their nodes: https://github.com/comfyanonymous/ComfyUI/pull/7167
