### ISSUE TITLE
The new "giant dinov2 image encoder" patch broke CLIP_VISION loading

### ISSUE THREAD

**Issue by wywywywy** [comfyanonymous/ComfyUI#7278]
### Expected Behavior

The "Load CLIP Vision" node should load checkpoints (e.g. `clip_vision_h.safetensors`) like previous commits.

### Actual Behavior

It shows the error below

### Steps to Reproduce

Just load a CLIP vision checkpoint

### Debug Logs

```powershell
!!! Exception during processing !!! 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/wywywywy/ai/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/wywywywy/ai/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/wywywywy/ai/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/wywywywy/ai/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/wywywywy/ai/ComfyUI/nodes.py", line 1008, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)
  File "/home/wywywywy/ai/ComfyUI/comfy/clip_vision.py", line 142, in load
    return load_clipvision_from_sd(sd)
  File "/home/wywywywy/ai/ComfyUI/comfy/clip_vision.py", line 126, in load_clipvision_from_sd
    clip = ClipVisionModel(json_config)
  File "/home/wywywywy/ai/ComfyUI/comfy/clip_vision.py", line 55, in __init__
    self.model = model_class(config, self.dtype, offload_device, comfy.ops.manual_cast)
TypeError: 'NoneType' object is not callable
```

### Other

Perhaps we're missing a default value to specify the type for backward compatibility?

**Comment by wywywywy** [comment]
I think this should be `clip_vision_model` not `clip_vision`

https://github.com/comfyanonymous/ComfyUI/blob/6dc7b0bfe3cd44302444f0f34db0e62b86764482/comfy/clip_vision.py#L39

    "clip_vision_model": comfy.clip_model.CLIPVisionModelProjection,

**Comment by wywywywy** [comment]
Also here

https://github.com/comfyanonymous/ComfyUI/blob/6dc7b0bfe3cd44302444f0f34db0e62b86764482/comfy/clip_vision.py#L51

**Comment by A-2-H** [comment]
Worked after changing to "clip_vision_model"

**Comment by LukeG89** [comment]
Ping @comfyanonymous 

For everyone, as a temporary solution, you can revert to the previous commit.

Open terminal in **ComfyUI** folder and run this command:
```
git reset --hard e8e990d6b8b5c813c87d1aeaed3e5110c7aba166
```

**Comment by somenewaccountthen** [comment]
Same problem here.
Came here to check what it us.

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by laraveber** [comment]
It still does not work ...

**Comment by laraveber** [comment]
Thank you. But unfortunately it did not solve my problem. My Dualcliploade knot just does not work. No mistake is shown, but the process stops on this node. It seems to me that he does not interact with t5xxl_fp16 and I do not know what's the matter. Everything worked before the Comfy update...

**Comment by merecesarchviz** [comment]
I have this error for 4 days already i update everyday the comfyui hoping it be solved, but apparently still have this bug!?
