### ISSUE TITLE
Invalid workflow against zod schema:

### ISSUE THREAD

**Issue by licedy** [comfyanonymous/ComfyUI#7309]
### Your question

I've just started using ComfyUI. I've noticed that when I load a lot of workflows, this error message keeps popping up. It doesn't seem to affect the actual operation of the workflows, but it keeps appearing every time I switch pages. I've spent a whole day searching online for a solution, but I still can't figure it out. I'm going crazy! I urgently need help.

![Image](https://github.com/user-attachments/assets/7ebc46ed-80b0-47f0-8a80-0667b5938db6)

For easier viewing:
Invalid workflow against zod schema:
Validation error: 
Invalid semantic version (x.y.z) at "nodes[8].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[14].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[15].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[17].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[18].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[20].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[22].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[25].properties.ver"; 
Invalid semantic version (x.y.z) at "nodes[26].properties.ver"

### Logs

```powershell

```

**Comment by ltdrdata** [comment]
Please upload the workflow file.

**Comment by ahmed-meligy** [comment]
I have the same issue

**Comment by christian-byrne** [comment]
To disable workflow validation you can toggle this setting off:

![Image](https://github.com/user-attachments/assets/f56e90e1-7a89-4078-ac59-04e945235d9e)

Workflow validation checks whether all aspects of the workflow adhere to the expected format/schema. It's okay to disable temporarily.

In your case, the validation is flagging the node's `ver` property (node pack version). `ver` is expected to be a semantic version like `1.2.3-beta.1+metadata`.

The validation for that field was added here https://github.com/Comfy-Org/ComfyUI_frontend/pull/2751. It uses this regex `/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([\da-z-]+(?:\.[\da-z-]+)*))?(?:\+([\da-z-]+(?:\.[\da-z-]+)*))?$/`. If you can share the workflow or the `ver` field of the node properties you may help find a bug in the current system, thanks!

**Comment by christian-byrne** [comment]
If someone who experiences this issue could share the workflow (or just the node inside the workflow that causes the issue), that would help a ton 🙏 !

**Comment by ahmed-meligy** [comment]
That's fix my issue, anyway here is a simple workflow @christian-byrne 

[Text2Image Styles.json](https://github.com/user-attachments/files/19362943/Text2Image.Styles.json)

**Comment by licedy** [comment]
After disabling workflow validation, there are no more error messages. Thank you!

**Comment by karl-von-knecht** [comment]
I am still getting these, here is a workflow
[Tagging with IF Image to Prompt.json](https://github.com/user-attachments/files/19807483/Tagging.with.IF.Image.to.Prompt.json)

![Image](https://github.com/user-attachments/assets/4b0264b4-d975-4dc6-ba0c-317b9ea01fbf)

**Comment by Hantiun** [comment]
> To disable workflow validation you can toggle this setting off:
> 
> ![Image](https://github.com/user-attachments/assets/f56e90e1-7a89-4078-ac59-04e945235d9e)
> 
> Workflow validation checks whether all aspects of the workflow adhere to the expected format/schema. It's okay to disable temporarily.
> 
> In your case, the validation is flagging the node's `ver` property (node pack version). `ver` is expected to be a semantic version like `1.2.3-beta.1+metadata`.
> 
> The validation for that field was added here [Comfy-Org/ComfyUI_frontend#2751](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2751). It uses this regex `/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([\da-z-]+(?:\.[\da-z-]+)*))?(?:\+([\da-z-]+(?:\.[\da-z-]+)*))?$/`. It also allows git commit hashes. If you can share the workflow or the `ver` field of the node properties you may help find a bug in the current system, thanks!

Thank u! After disabling workflow validation, there are no more error messages.

**Comment by christian-byrne** [comment]
This has been fixed on the current version of ComfyUI. So, you should not need to disable workflow validation anymore unless you're using an older version.

**Comment by brummerke** [comment]
I downloaded a workflow off of civitai. I'm getting this  error with it nonstop.
I'm on ComfyUI Manager V3.31.10. I have attached the file.

[Self-Sufficient Workflow (Anime) - Basic + Face + Hand Detailer.json](https://github.com/user-attachments/files/19821830/Self-Sufficient.Workflow.Anime.-.Basic.%2B.Face.%2B.Hand.Detailer.json)

**Comment by christian-byrne** [comment]
> I am still getting these, here is a workflow

Thank you for providing the workflow. This was a new issue that had not been seen before but we fixed it in on the latest version of the Manager: https://github.com/Comfy-Org/ComfyUI-Manager/pull/1758

**Comment by christian-byrne** [comment]
- Fixed @karl-von-knecht issue here: https://github.com/Comfy-Org/ComfyUI-Manager/pull/1758
- Fixed @brummerke issues here: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3518

Thanks for sharing workflows and helping improve the ecosystem. It's important we ensure the node pack name/version is formatted correctly and handles all edge cases, so that installing custom nodes is a smooth process.

Anyone else arriving, please post workflows, it is very much appreciated!

**Comment by euss3** [comment]
I still have the same error: win 11, Invalid workflow against zod schema:
Validation error: Invalid format. Must be 'github-user/repo-name' at "nodes[0].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[5].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[6].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[7].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[10].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[11].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[14].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[16].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[22].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[23].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[35].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[39].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[41].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[44].properties.aux_id"; Invalid format. Must be 'github-user/repo-name' at "nodes[45].properties.aux_id"

[workflow-mpswan-funv3-RqB562nEkWngLE8I9p6t-t8star-openart.ai.json](https://github.com/user-attachments/files/20028399/workflow-mpswan-funv3-RqB562nEkWngLE8I9p6t-t8star-openart.ai.json) Here are more details: 
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-05-04 18:47:41.108
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: C:\Users\amin\Desktop\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI
** User directory: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 32607 MB, total RAM 63092 MB
pytorch version: 2.8.0.dev20250502+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
Using pytorch attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.31
ComfyUI frontend version: 1.18.6
[Prompt Server] web root: C:\Users\amin\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static
[Crystools INFO] Crystools version: 1.22.1
[Crystools INFO] CPU: AMD Ryzen 9 9950X3D 16-Core Processor - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 5090
[Crystools INFO] NVIDIA Driver: 576.02
xFormers not available
xFormers not available
[ComfyUI-Easy-Use] server: v1.3.0 Loaded
[ComfyUI-Easy-Use] web root: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\web_version/v1 Loaded
ComfyUI-GGUF: Allowing full torch compile (nightly)
### Loading: ComfyUI-Impact-Pack (V8.14.2)
[Impact Pack] Wildcards loading done.
Total VRAM 32607 MB, total RAM 63092 MB
pytorch version: 2.8.0.dev20250502+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V3.31.13)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 150 [76899171] *DETACHED | Released on '2025-05-03'
Warning: Could not load sageattention: No module named 'sageattention'
sageattention package is not installed
Warning: Could not load sageattention: No module named 'sageattention'
sageattention package is not installed
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉


Import times for custom nodes:
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-textoverlay
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\gguf
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-depthanythingv2
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoStartEndFrames
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-kjnodes
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-videohelpersuite
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
   0.2 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
   0.4 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use

Starting server

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH ComfyRegistry Data: 5/83
FETCH ComfyRegistry Data: 10/83
FETCH ComfyRegistry Data: 15/83
FETCH ComfyRegistry Data: 20/83
[ComfyUI-Manager] Installation failed:
Install path already exists: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper

[ComfyUI-Manager] Queued works are completed.
{'install': 1}

After restarting ComfyUI, please refresh the browser.
FETCH ComfyRegistry Data: 25/83

Restarting... [Legacy Mode]


Command: ['"C:\\Users\\amin\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe"', '"ComfyUI\\main.py"']

C:\Users\amin\Desktop\ComfyUI_windows_portable>--use-sage-attention
'--use-sage-attention' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\amin\Desktop\ComfyUI_windows_portable>pause
Press any key to continue . . . [START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-05-04 18:48:07.840
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: C:\Users\amin\Desktop\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI
** User directory: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use
   2.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 32607 MB, total RAM 63092 MB
pytorch version: 2.8.0.dev20250502+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
Using pytorch attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.31
ComfyUI frontend version: 1.18.6
[Prompt Server] web root: C:\Users\amin\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static
[Crystools INFO] Crystools version: 1.22.1
[Crystools INFO] CPU: AMD Ryzen 9 9950X3D 16-Core Processor - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 5090
[Crystools INFO] NVIDIA Driver: 576.02
xFormers not available
xFormers not available
[ComfyUI-Easy-Use] server: v1.3.0 Loaded
[ComfyUI-Easy-Use] web root: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use\web_version/v1 Loaded
ComfyUI-GGUF: Allowing full torch compile (nightly)
### Loading: ComfyUI-Impact-Pack (V8.14.2)
[Impact Pack] Wildcards loading done.
Total VRAM 32607 MB, total RAM 63092 MB
pytorch version: 2.8.0.dev20250502+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V3.31.13)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 150 [76899171] *DETACHED | Released on '2025-05-03'
Warning: Could not load sageattention: No module named 'sageattention'
sageattention package is not installed
Warning: Could not load sageattention: No module named 'sageattention'
sageattention package is not installed
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉


Import times for custom nodes:
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-textoverlay
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\gguf
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-depthanythingv2
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoStartEndFrames
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-kjnodes
   0.0 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-videohelpersuite
   0.1 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
   0.4 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
   0.5 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-easy-use
   0.5 seconds: C:\Users\amin\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH ComfyRegistry Data: 5/83
FETCH ComfyRegistry Data: 10/83
FETCH ComfyRegistry Data: 15/83
FETCH ComfyRegistry Data: 20/83
FETCH ComfyRegistry Data: 25/83
FETCH ComfyRegistry Data: 30/83
FETCH ComfyRegistry Data: 35/83
FETCH ComfyRegistry Data: 40/83
FETCH ComfyRegistry Data: 45/83
FETCH ComfyRegistry Data: 50/83
FETCH ComfyRegistry Data: 55/83
FETCH ComfyRegistry Data: 60/83
FETCH ComfyRegistry Data: 65/83
FETCH ComfyRegistry Data: 70/83
FETCH ComfyRegistry Data: 75/83
FETCH ComfyRegistry Data: 80/83
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.

**Comment by CGgangzi** [comment]
l来信已收到..缓后回复....

**Comment by alastaira** [comment]
Also getting this error, also using the Reactor Masking Node as @logan683 above

**Comment by andypotato** [comment]
I'm still getting tons of these errors when developing my own nodes that have not been published (yet) to any registry or Github. This validation feature may be well-intended, but it's quite annoying to have it pop up over and over again during development.

**Comment by christian-byrne** [comment]
You can disable it, see my comments above.

**Comment by duracell80** [comment]
If you are getting this with a ControlNet try this:

Change:
"aux_id": "comfyui_controlnet_aux/",

To:
"aux_id": "Fannovel16/comfyui_controlnet_aux",

This worked for me, by:

- Exporting the workflow to my Downloads folder
- Open the JSON from there
- Edit the aux_id
- Save the file and delete the workflow from Comfy
- Import the JSON back into Comfy and save
