### ISSUE TITLE
HiDream E1 isn't working at all - ComfyUI portable

### ISSUE THREAD

**Issue by MoonMoon82** [comfyanonymous/ComfyUI#7868]
### Expected Behavior

I expect to get another image, based on the input image and following the prompt

### Actual Behavior

The resulting image doesn't even look like the input image

### Steps to Reproduce

If CFG value is raised to ~5 or ~6, the output image isn't noise anymore, but still has nothing to do with the input image
![Image](https://github.com/user-attachments/assets/e761ea74-8fe2-4e37-9d43-d2275ef3cc9e)

### Debug Logs

```powershell
E:\StableDiffusion\ComfyUI_port>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen --disable-auto-launch --preview-method taesd
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-04-29 18:53:05.883
** Platform: Windows
** Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
** Python executable: E:\StableDiffusion\ComfyUI_port\python_embeded\python.exe
** ComfyUI Path: E:\StableDiffusion\ComfyUI_port\ComfyUI
** ComfyUI Base Folder Path: E:\StableDiffusion\ComfyUI_port\ComfyUI
** User directory: E:\StableDiffusion\ComfyUI_port\ComfyUI\user
** ComfyUI-Manager config path: E:\StableDiffusion\ComfyUI_port\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: E:\StableDiffusion\ComfyUI_port\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   3.8 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 24575 MB, total RAM 65459 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch attention
Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.3.29
ComfyUI frontend version: 1.16.9
[Prompt Server] web root: E:\StableDiffusion\ComfyUI_port\python_embeded\Lib\site-packages\comfyui_frontend_package\static
[Crystools INFO] Crystools version: 1.22.1
[Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 560.94
ComfyUI-GGUF: Partial torch compile only, consider updating pytorch
### Loading: ComfyUI-Inspire-Pack (V1.18)
Total VRAM 24575 MB, total RAM 65459 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V3.31.13)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.29-26-g2d6805ce | Released on '2025-04-22'
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-LTXVideo
MultiGPU: Module ComfyUI-LTXVideo not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-ltxvideo
MultiGPU: Module comfyui-ltxvideo not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Florence2
MultiGPU: Module ComfyUI-Florence2 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-florence2
MultiGPU: Module comfyui-florence2 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui_bitsandbytes_nf4
MultiGPU: Module comfyui_bitsandbytes_nf4 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\x-flux-comfyui
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\x-flux-comfyui
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-MMAudio
MultiGPU: Module ComfyUI-MMAudio not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-mmaudio
MultiGPU: Module comfyui-mmaudio not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-GGUF
MultiGPU: Found ComfyUI-GGUF, creating compatible MultiGPU nodes
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\PuLID_ComfyUI
MultiGPU: Module PuLID_ComfyUI not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\pulid_comfyui
MultiGPU: Module pulid_comfyui not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
MultiGPU: Module ComfyUI-HunyuanVideoWrapper not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-hunyuanvideowrapper
MultiGPU: Module comfyui-hunyuanvideowrapper not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
MultiGPU: Module ComfyUI-WanVideoWrapper not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-wanvideowrapper
MultiGPU: Module comfyui-wanvideowrapper not found - skipping
MultiGPU: Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, MergeFluxLoRAsQuantizeAndLoaddMultiGPU, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, QuadrupleCLIPLoaderMultiGPU, CLIPVisionLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU, QuadrupleCLIPLoaderGGUFMultiGPU, QuadrupleCLIPLoaderGGUFDisTorchMultiGPU
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
Searge-SDXL v4.3.1 in E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "The journey of a thousand miles begins with one step." - Lao Tzu


Import times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-WanVideoKsampler
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\teacache
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-multigpu
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\gguf
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui_essentials
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-kjnodes
   0.1 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-inspire-pack
   0.2 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-videohelpersuite
   0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-manager
   0.6 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.7 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\SeargeSDXL
   0.8 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI_RH_FramePack
   0.8 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-advancedliveportrait
   1.6 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
To see the GUI go to: http://[::]:8188
FETCH ComfyRegistry Data: 5/83
FETCH ComfyRegistry Data: 10/83
FETCH ComfyRegistry Data: 15/83
FETCH ComfyRegistry Data: 20/83
FETCH ComfyRegistry Data: 25/83
FETCH ComfyRegistry Data: 30/83
FETCH ComfyRegistry Data: 35/83
FETCH ComfyRegistry Data: 40/83
FETCH ComfyRegistry Data: 45/83
FETCH ComfyRegistry Data: 50/83
FETCH ComfyRegistry Data: 55/83
FETCH ComfyRegistry Data: 60/83
FETCH ComfyRegistry Data: 65/83
FETCH ComfyRegistry Data: 70/83
FETCH ComfyRegistry Data: 75/83
FETCH ComfyRegistry Data: 80/83
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load AutoencodingEngine
loaded completely 19172.0 159.87335777282715 True
Using scaled fp8: fp8 matrix mult: False, scale input: False
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load HiDreamTEModel_
loaded completely 21664.926642227172 13887.293487548828 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLOW
Requested to load HiDream
loaded completely 18456.674736785888 16313.298400878906 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:53<00:00,  1.80s/it]
Requested to load AutoencodingEngine
loaded completely 288.7563591003418 159.87335777282715 True
Prompt executed in 105.75 seconds
```

**Comment by isaac-mcfadyen** [comment]
HiDream needs a shift of 3, trying adding a `ModelSamplingSD3` node set to 3.0 between the `Load Diffusion Model` and the `KSampler`.

**Comment by MoonMoon82** [comment]
@isaac-mcfadyen Even though it isn't just noise anymore, it still has nothing to do with the input image:

![Image](https://github.com/user-attachments/assets/fee24345-c6cd-41ef-8eff-9c68b2cfe888)

**Comment by MoonMoon82** [comment]
Right before someone asks about the VAE encoder:

![Image](https://github.com/user-attachments/assets/fa097a9e-9663-4fde-a180-1cc1db6ff6b8)

It doesn't make any difference

**Comment by arcum42** [comment]
One thing that does stand out to me is that your cfg is set to 1.0, and the model says "full"...

**Comment by isaac-mcfadyen** [comment]
Also HiDream E1 says they want the instructions given in a specific format per https://huggingface.co/HiDream-ai/HiDream-E1-Full, it should be `Editing Instruction: {instruction}. Target Image Description: {description}`

**Comment by nikolaiusa** [comment]
768*768?

**Comment by MoonMoon82** [comment]
@nikolaiusa It seems the resolution doesn't effect the result. (See screenshot below)
@isaac-mcfadyen I tried different prompts without any effect.
@arcum42 As I already wrote the CFG value doesn't matter:
![Image](https://github.com/user-attachments/assets/433a7264-f3c3-4b48-98ec-606fbdf3af20)

**Comment by MoonMoon82** [comment]
It seems the input image is ignored completely! No matter which input image I use, as long the seed stays the same, the resulting image always stays the same:

![Image](https://github.com/user-attachments/assets/4a95ff7d-acfc-4c82-9e5c-9ccae6d8f6f3)

![Image](https://github.com/user-attachments/assets/259b9579-80a1-4307-9fe9-9ab33db0f3f2)

**Comment by radovan-tuma** [comment]
> It seems the input image is ignored completely! No matter which input image I use, as long the seed stays the same, the resulting image always stays **exactly** the same:

I had to switch ComfyUI to nightly and update it. Now it is working for me. 


> Also HiDream E1 says they want the instructions given in a specific format per https://huggingface.co/HiDream-ai/HiDream-E1-Full, it should be `Editing Instruction: {instruction}. Target Image Description: {description}`

I have tried it with and without "Editing instruction:" and it works the same, maybe it is only needed if you use editing instruction and target image description at the same time.

![Image](https://github.com/user-attachments/assets/91c376ea-7063-4db2-a23d-e880b1d7b4d9)

**Comment by MoonMoon82** [comment]
@radovan-tuma Unfortunately it seems switching to comfyui nightly has also no effect:

![Image](https://github.com/user-attachments/assets/9468a1c2-d1af-42c4-8ebe-35b54fccf9db)

![Image](https://github.com/user-attachments/assets/4859a218-fe2d-410b-98a2-da2058eb033d)




```
E:\StableDiffusion\ComfyUI_port>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen --disable-auto-launch --preview-method taesd
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-04-30 16:00:57.257
** Platform: Windows
** Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
** Python executable: E:\StableDiffusion\ComfyUI_port\python_embeded\python.exe
** ComfyUI Path: E:\StableDiffusion\ComfyUI_port\ComfyUI
** ComfyUI Base Folder Path: E:\StableDiffusion\ComfyUI_port\ComfyUI
** User directory: E:\StableDiffusion\ComfyUI_port\ComfyUI\user
** ComfyUI-Manager config path: E:\StableDiffusion\ComfyUI_port\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: E:\StableDiffusion\ComfyUI_port\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   3.8 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 24575 MB, total RAM 65459 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch attention
Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.3.29
ComfyUI frontend version: 1.16.9
[Prompt Server] web root: E:\StableDiffusion\ComfyUI_port\python_embeded\Lib\site-packages\comfyui_frontend_package\static
[Crystools INFO] Crystools version: 1.22.1
[Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 560.94
ComfyUI-GGUF: Partial torch compile only, consider updating pytorch
### Loading: ComfyUI-Inspire-Pack (V1.18)
Total VRAM 24575 MB, total RAM 65459 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V3.31.13)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.29-26-g2d6805ce | Released on '2025-04-22'
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-LTXVideo
MultiGPU: Module ComfyUI-LTXVideo not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-ltxvideo
MultiGPU: Module comfyui-ltxvideo not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Florence2
MultiGPU: Module ComfyUI-Florence2 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-florence2
MultiGPU: Module comfyui-florence2 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui_bitsandbytes_nf4
MultiGPU: Module comfyui_bitsandbytes_nf4 not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\x-flux-comfyui
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\x-flux-comfyui
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-MMAudio
MultiGPU: Module ComfyUI-MMAudio not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-mmaudio
MultiGPU: Module comfyui-mmaudio not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-GGUF
MultiGPU: Found ComfyUI-GGUF, creating compatible MultiGPU nodes
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\PuLID_ComfyUI
MultiGPU: Module PuLID_ComfyUI not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\pulid_comfyui
MultiGPU: Module pulid_comfyui not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
MultiGPU: Module ComfyUI-HunyuanVideoWrapper not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-hunyuanvideowrapper
MultiGPU: Module comfyui-hunyuanvideowrapper not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
MultiGPU: Module ComfyUI-WanVideoWrapper not found - skipping
MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-wanvideowrapper
MultiGPU: Module comfyui-wanvideowrapper not found - skipping
MultiGPU: Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, MergeFluxLoRAsQuantizeAndLoaddMultiGPU, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, QuadrupleCLIPLoaderMultiGPU, CLIPVisionLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU, QuadrupleCLIPLoaderGGUFMultiGPU, QuadrupleCLIPLoaderGGUFDisTorchMultiGPU
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
Searge-SDXL v4.3.1 in E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Challenges are what make life interesting and overcoming them is what makes life meaningful." - Joshua J. Marine


Import times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-WanVideoKsampler
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\teacache
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-multigpu
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\gguf
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-kjnodes
   0.1 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-inspire-pack
   0.2 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-videohelpersuite
   0.3 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui_essentials
   0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-manager
   0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI_RH_FramePack
   0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.6 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\SeargeSDXL
   0.7 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-advancedliveportrait
   1.6 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
To see the GUI go to: http://[::]:8188
FETCH ComfyRegistry Data: 5/83
FETCH ComfyRegistry Data: 10/83
FETCH ComfyRegistry Data: 15/83
FETCH ComfyRegistry Data: 20/83
FETCH ComfyRegistry Data: 25/83
FETCH ComfyRegistry Data: 30/83
FETCH ComfyRegistry Data: 35/83
FETCH ComfyRegistry Data: 40/83
FETCH ComfyRegistry Data: 45/83
FETCH ComfyRegistry Data: 50/83
FETCH ComfyRegistry Data: 55/83
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Using scaled fp8: fp8 matrix mult: False, scale input: False
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
FETCH ComfyRegistry Data: 60/83
FETCH ComfyRegistry Data: 65/83
FETCH ComfyRegistry Data: 70/83
FETCH ComfyRegistry Data: 75/83
Requested to load HiDreamTEModel_
FETCH ComfyRegistry Data: 80/83
loaded completely 21886.8 13887.293487548828 True
Requested to load AutoencodingEngine
loaded completely 6758.706497192383 159.87335777282715 True
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.jsonmodel weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLOW
 [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
Requested to load HiDream
loaded completely 17952.6747215271 16313.298400878906 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:28<00:00,  1.15s/it]
Requested to load AutoencodingEngine
loaded completely 175.18201446533203 159.87335777282715 True
Prompt executed in 82.41 seconds
```

**Comment by radovan-tuma** [comment]
> [@radovan-tuma](https://github.com/radovan-tuma) Unfortunately it seems switching to comfyui nightly has also no effect:
> 
> ComfyUI version: 0.3.29

My ComfyUI vercion is 0.3.30.
I am not using portable version, maybe try to run update_comfyui.bat script. It should be located in E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\update.

**Comment by Amazon90** [comment]
https://openart.ai/workflows/makisekurisu/hidream-image-edit-native-support/GdVYrgZdSBsRK8La8eSs

**Comment by MoonMoon82** [comment]
@Amazon90 There's no essential difference in the workflows.

@radovan-tuma I'm updating several times a day as soon I see some new commits. I don't know why I'm still on 0.3.29 :-( .. I assume it has something to do with the portabel version. To change the "Update"-option to "ComfyUI Nightly Version" doesn't seem to effect the update process.

**Comment by sipie800** [comment]
Nothing to do with comfyui. hidream-e1 can't do that by itself. Its capability is not as large as its checkpoint. Fake hair texture, unrelated style converting...and many other comfusing features. Quite frustrating, anyway maybe it is the new thing though.

**Comment by Amazon90** [comment]
> @radovan-tuma Unfortunately it seems switching to comfyui nightly has also no effect:
> 
> ![Image](https://github.com/user-attachments/assets/9468a1c2-d1af-42c4-8ebe-35b54fccf9db)
> 
> ![Image](https://github.com/user-attachments/assets/4859a218-fe2d-410b-98a2-da2058eb033d)
> 
> 
> 
> 
> ```
> E:\StableDiffusion\ComfyUI_port>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen --disable-auto-launch --preview-method taesd
> [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2025-04-30 16:00:57.257
> ** Platform: Windows
> ** Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
> ** Python executable: E:\StableDiffusion\ComfyUI_port\python_embeded\python.exe
> ** ComfyUI Path: E:\StableDiffusion\ComfyUI_port\ComfyUI
> ** ComfyUI Base Folder Path: E:\StableDiffusion\ComfyUI_port\ComfyUI
> ** User directory: E:\StableDiffusion\ComfyUI_port\ComfyUI\user
> ** ComfyUI-Manager config path: E:\StableDiffusion\ComfyUI_port\ComfyUI\user\default\ComfyUI-Manager\config.ini
> ** Log path: E:\StableDiffusion\ComfyUI_port\ComfyUI\user\comfyui.log
> 
> Prestartup times for custom nodes:
>    3.8 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-manager
> 
> Checkpoint files will always be loaded safely.
> Total VRAM 24575 MB, total RAM 65459 MB
> pytorch version: 2.6.0+cu126
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
> Using pytorch attention
> Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
> ComfyUI version: 0.3.29
> ComfyUI frontend version: 1.16.9
> [Prompt Server] web root: E:\StableDiffusion\ComfyUI_port\python_embeded\Lib\site-packages\comfyui_frontend_package\static
> [Crystools INFO] Crystools version: 1.22.1
> [Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 11
> [Crystools INFO] Pynvml (Nvidia) initialized.
> [Crystools INFO] GPU/s:
> [Crystools INFO] 0) NVIDIA GeForce RTX 3090
> [Crystools INFO] NVIDIA Driver: 560.94
> ComfyUI-GGUF: Partial torch compile only, consider updating pytorch
> ### Loading: ComfyUI-Inspire-Pack (V1.18)
> Total VRAM 24575 MB, total RAM 65459 MB
> pytorch version: 2.6.0+cu126
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
> ### Loading: ComfyUI-Manager (V3.31.13)
> [ComfyUI-Manager] network_mode: public
> ### ComfyUI Version: v0.3.29-26-g2d6805ce | Released on '2025-04-22'
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-LTXVideo
> MultiGPU: Module ComfyUI-LTXVideo not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-ltxvideo
> MultiGPU: Module comfyui-ltxvideo not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Florence2
> MultiGPU: Module ComfyUI-Florence2 not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-florence2
> MultiGPU: Module comfyui-florence2 not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
> MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui_bitsandbytes_nf4
> MultiGPU: Module comfyui_bitsandbytes_nf4 not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\x-flux-comfyui
> MultiGPU: Module x-flux-comfyui not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\x-flux-comfyui
> MultiGPU: Module x-flux-comfyui not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-MMAudio
> MultiGPU: Module ComfyUI-MMAudio not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-mmaudio
> MultiGPU: Module comfyui-mmaudio not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-GGUF
> MultiGPU: Found ComfyUI-GGUF, creating compatible MultiGPU nodes
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\PuLID_ComfyUI
> MultiGPU: Module PuLID_ComfyUI not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\pulid_comfyui
> MultiGPU: Module pulid_comfyui not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
> MultiGPU: Module ComfyUI-HunyuanVideoWrapper not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-hunyuanvideowrapper
> MultiGPU: Module comfyui-hunyuanvideowrapper not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
> MultiGPU: Module ComfyUI-WanVideoWrapper not found - skipping
> MultiGPU: Checking for module at E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-wanvideowrapper
> MultiGPU: Module comfyui-wanvideowrapper not found - skipping
> MultiGPU: Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, MergeFluxLoRAsQuantizeAndLoaddMultiGPU, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, QuadrupleCLIPLoaderMultiGPU, CLIPVisionLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU, QuadrupleCLIPLoaderGGUFMultiGPU, QuadrupleCLIPLoaderGGUFDisTorchMultiGPU
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
> Xformers is not installed!
> Flash Attn is not installed!
> Sage Attn is not installed!
> Searge-SDXL v4.3.1 in E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\SeargeSDXL
> WAS Node Suite: OpenCV Python FFMPEG support is enabled
> WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
> WAS Node Suite: Finished. Loaded 220 nodes successfully.
> 
>         "Challenges are what make life interesting and overcoming them is what makes life meaningful." - Joshua J. Marine
> 
> 
> Import times for custom nodes:
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\websocket_image_save.py
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-WanVideoKsampler
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\teacache
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-multigpu
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\gguf
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-GGUF
>    0.0 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-kjnodes
>    0.1 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-inspire-pack
>    0.2 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-videohelpersuite
>    0.3 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui_essentials
>    0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-manager
>    0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI_RH_FramePack
>    0.5 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\ComfyUI-Crystools
>    0.6 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\SeargeSDXL
>    0.7 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\comfyui-advancedliveportrait
>    1.6 seconds: E:\StableDiffusion\ComfyUI_port\ComfyUI\custom_nodes\was-node-suite-comfyui
> 
> Starting server
> 
> To see the GUI go to: http://0.0.0.0:8188
> To see the GUI go to: http://[::]:8188
> FETCH ComfyRegistry Data: 5/83
> FETCH ComfyRegistry Data: 10/83
> FETCH ComfyRegistry Data: 15/83
> FETCH ComfyRegistry Data: 20/83
> FETCH ComfyRegistry Data: 25/83
> FETCH ComfyRegistry Data: 30/83
> FETCH ComfyRegistry Data: 35/83
> FETCH ComfyRegistry Data: 40/83
> FETCH ComfyRegistry Data: 45/83
> FETCH ComfyRegistry Data: 50/83
> FETCH ComfyRegistry Data: 55/83
> got prompt
> Using pytorch attention in VAE
> Using pytorch attention in VAE
> VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
> Using scaled fp8: fp8 matrix mult: False, scale input: False
> Using scaled fp8: fp8 matrix mult: False, scale input: False
> CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
> FETCH ComfyRegistry Data: 60/83
> FETCH ComfyRegistry Data: 65/83
> FETCH ComfyRegistry Data: 70/83
> FETCH ComfyRegistry Data: 75/83
> Requested to load HiDreamTEModel_
> FETCH ComfyRegistry Data: 80/83
> loaded completely 21886.8 13887.293487548828 True
> Requested to load AutoencodingEngine
> loaded completely 6758.706497192383 159.87335777282715 True
> FETCH ComfyRegistry Data [DONE]
> [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
> FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.jsonmodel weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
> model_type FLOW
>  [DONE]
> [ComfyUI-Manager] All startup tasks have been completed.
> Requested to load HiDream
> loaded completely 17952.6747215271 16313.298400878906 True
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:28<00:00,  1.15s/it]
> Requested to load AutoencodingEngine
> loaded completely 175.18201446533203 159.87335777282715 True
> Prompt executed in 82.41 seconds
> ```

I don’t know where your confidence comes from in saying there’s no essential difference. First, using CFG=1 instead of 5 is simply wrong. Second, the prompt should be written in the official format.

**Comment by camoody1** [comment]
@MoonMoon82 I'm having the same issue. I'm using the workflow from the Comfy website and my output image has ZERO in common with my starting image. Something is obviously a problem with our environments if others are working fine.

**Comment by MoonMoon82** [comment]
@camoody1 Thank you for your feedback! Now I know at least I'm not the only one who got this issue.
Have you tried to change the input image and recognized that the output image doesn't change?
Are you also using the stand-alone version of ComyUI?

**Comment by camoody1** [comment]
> [@camoody1](https://github.com/camoody1) Thank you for your feedback! Now I know at least I'm not the only one who got this issue. Have you tried to change the input image and recognized that the output image doesn't change? Are you also using the stand-alone version of ComyUI?

I am using ComfyUI Portable. I've changed the input image and nothing changed on the output. It seems to only use the text prompt in its image creation for me.

**Comment by Clusters** [comment]
I tried this tutorial with the newest stable and it works with my 3090 and cu124. But the results are not that impressive, if you're not bruteforcing them.
https://docs.comfy.org/tutorials/advanced/hidream-e1

![Image](https://github.com/user-attachments/assets/589f11a6-b9aa-484e-aab7-611c3cba10cc)
one of the better results (the seed was 41)

**Comment by camoody1** [comment]
@Clusters Change the Upscale Image from Bilinear to Bicubic and see if it makes any difference. I saw a video earlier claiming that it did.

**Comment by Clusters** [comment]
@camoody1 I can reproduce the example from the tutorial using the seed from the tutorial. But any other seed gives me worse result. And on the 3090, I can't test that fast to find how often a "good" seed can be achieved.

However, if a good result, like Seed 41 from my above post, the Bicubic method seems to give me a bit more details in the result. But it unfortunately does not fix the inconsistency in the results for me.

**Comment by Crumplecorn** [comment]
I had this issue on comfyui portable despite being fully updated, resolved by starting over with a fresh portable 'install'.

**Comment by MoonMoon82** [comment]
I downloaded the latest windows portable 7z and added all necessary model files.
NOW IT WORKS!
I still don't know why it didn't work with my previous version of the comfyUI portable, but at least now I'm on the latest ComfyUI version 0.3.31 instead of 0.3.29.
Is it correct that update_comfyui.bat does not update to the latest release?

![Image](https://github.com/user-attachments/assets/01007464-3a00-4401-bffe-d703a9077bf2)

```
Checkpoint files will always be loaded safely.
Total VRAM 24575 MB, total RAM 65459 MB
pytorch version: 2.7.0+cu128
Enabled fp16 accumulation.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.31
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
ComfyUI frontend version: 1.18.6
[Prompt Server] web root: E:\StableDiffusion\ComfyUI_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static

Import times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Using scaled fp8: fp8 matrix mult: False, scale input: False
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load HiDreamTEModel_
loaded completely 21886.8 13887.293487548828 True
Requested to load AutoencodingEngine
loaded completely 6758.706497192383 159.87335777282715 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLOW
Requested to load HiDream
loaded completely 17952.674820709228 16313.298400878906 True
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [02:16<00:00,  4.87s/it]
Requested to load AutoencodingEngine
loaded partially 155.66887283325195 155.668701171875 0
Prompt executed in 181.80 seconds
```

**Comment by camoody1** [comment]
@MoonMoon82 It's nice that it works for you, but that result looks VERY different from the starting image. I don't know how helpful this tool is.

**Comment by radovan-tuma** [comment]
@MoonMoon82 Great to hear it's finally working for you. 
@MoonMoon82 & @camoody1 If you want to change image just a little, just to change or add a detail, it is important to keep the prompt simple and avoid confusion if you want to change the whole image to CG graphics and ultra realism. If you shorten the prompt to "Let the girl put on the VR glasses full of a sense of technology, just like the scenes in Ready Player One." It would much more like the original image with VR glasses.

![Image](https://github.com/user-attachments/assets/6d91c562-242b-49d5-94e9-64d5a825213c)

**Comment by pizurny** [comment]
If anyone is still fighting this issue, just update comfy portable with update  .bat scripts, that worked for me
